/**
 * DNK Artisan 2.0 Language Store
 * 5-Dialect Localization System (Hindi, Kannada, Tamil, Bengali, English)
 * with low-literacy Voice/Audio narration support.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import { create } from 'zustand';
import { APP_CONFIG, SUPPORTED_LANGUAGES } from '../constants/Config';

export type SupportedLanguage = 'hi' | 'kn' | 'ta' | 'bn' | 'en';

interface LanguageState {
  currentLang: SupportedLanguage;
  isSpeaking: boolean;
  setLanguage: (lang: SupportedLanguage) => Promise<void>;
  hydrateLanguage: () => Promise<void>;
  t: (key: string) => string;
  speakText: (text: string) => Promise<void>;
  stopSpeaking: () => Promise<void>;
}

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  hi: {
    // App & Branding
    app_title: 'डाक घर निर्यात केंद्र',
    app_subtitle: 'शिल्पकार निर्यात पोर्टल',
    india_post: 'भारतीय डाक',
    dept_posts: 'डाक विभाग, संचार मंत्रालय',

    // Splash & Auth
    splash_badge: 'भारतीय डाक • डाक घर निर्यात केंद्र',
    splash_tagline: 'अपने हस्तशिल्प को दें वैश्विक बाज़ार',
    splash_btn_start: 'शुरू करें (Login)',
    splash_pillar_1_title: '1. फोटो खींचें',
    splash_pillar_1_desc: 'अपने शिल्प की फोटो लें, एआई स्टूडियो बैकग्राउंड साफ़ करेगा।',
    splash_pillar_2_title: '2. आवाज़ से बताएं',
    splash_pillar_2_desc: 'अपनी मातृभाषा में बोलें, भाषा एवं तकनीकी विवरण स्वतः दर्ज होगा।',
    splash_pillar_3_title: '3. डाकघर ड्रॉप-ऑफ',
    splash_pillar_3_desc: 'निकटतम डाकघर में पार्सल जमा करें और अंतरराष्ट्रीय खरीदारों तक पहुंचाएं।',
    splash_footer: 'संचार मंत्रालय • भारत सरकार • डिजिटल इंडिया',
    login_title: 'शिल्पकार लॉगिन',
    login_sub: 'अपना पंजीकृत मोबाइल नंबर दर्ज करें',
    login_phone_tab: 'मोबाइल नंबर',
    login_email_tab: 'ईमेल',
    mobile_num: 'मोबाइल नंबर',
    email_addr: 'ईमेल पता',
    enter_phone: '10-अंकीय मोबाइल नंबर',
    btn_get_otp: 'ओटीपी प्राप्त करें',
    sending_otp: 'ओटीपी भेजा जा रहा है...',
    verify_otp_title: 'ओटीपी सत्यापन',
    verify_otp_sub: 'दर्ज किए गए नंबर पर भेजा गया 6-अंकीय कोड दर्ज करें',
    otp_code: 'ओटीपी कोड',
    btn_verify: 'सत्यापित करें एवं आगे बढ़ें',
    verifying: 'सत्यापन हो रहा है...',
    resend_otp: 'ओटीपी पुनः भेजें',
    resend_in: 'पुनः भेजें',
    select_language: 'भाषा चुनें',
    choose_dialect: 'मातृभाषा चुनें',
    change_number: 'नंबर बदलें',
    invalid_otp: 'कृपया 6 अंकों का मान्य ओटीपी दर्ज करें',

    // Navigation Tabs
    tab_dashboard: 'डैशबोर्ड',
    tab_studio: 'एआई स्टूडियो',
    tab_orders: 'ऑर्डर एवं क्यूआर',
    tab_dropoff: 'डाकघर ड्रॉप-ऑफ',
    tab_products: 'मेरे उत्पाद',

    // Dashboard
    greeting_artisan: 'नमस्ते, शिल्पकार जी',
    kpi_active_products: 'सक्रिय उत्पाद',
    kpi_total_earnings: 'कुल आय (INR)',
    kpi_pending_dropoff: 'ड्रॉप-ऑफ बाकी',
    kpi_market_leads: 'बाज़ार अवसर (Market Opportunities)',
    add_btn: 'जोड़ें',
    quick_action_add: 'नया उत्पाद जोड़ें',
    quick_action_dropoff: 'निकटतम डाकघर खोजें',
    quick_action_orders: 'ऑर्डर एवं लेबल्स',
    section_active_catalog: 'सक्रिय उत्पाद सूची',
    section_market_opps: 'SIH26090 बाज़ार मांग (Opportunities)',
    section_recent_orders: 'हाल के ऑर्डर',
    view_all: 'सभी देखें',
    no_products_title: 'अभी कोई उत्पाद नहीं है',
    no_products_sub: 'एआई स्टूडियो की सहायता से अपना पहला हस्तशिल्प उत्पाद जोड़ें।',
    no_orders_title: 'अभी कोई नया ऑर्डर नहीं है',
    no_orders_sub: 'जब विदेशी खरीदार आपके उत्पाद खरीदेंगे, वे यहाँ दिखाई देंगे।',
    no_opps_title: 'कोई सक्रिय मांग नहीं',
    no_opps_sub: 'वर्तमान में कोई नया थोक ऑर्डर उपलब्ध नहीं है।',
    btn_retry: 'पुनः प्रयास करें',

    // AI Studio & Guided Camera
    studio_wizard_title: 'एआई स्टूडियो एवं आवाज़ कैटलॉग',
    step_camera: '1. फोटो खींचें',
    step_enhance: '2. एआई संपादन',
    step_voice: '3. आवाज़ से बताएं',
    step_review: '4. समीक्षा करें',
    step_pricing: '5. बहु-चैनल मूल्य निर्धारण',
    camera_step_sub: 'अपने हस्तशिल्प की स्पष्ट फोटो लें। केंद्र में रखें।',
    enhance_step_sub: 'एआई विजन स्टूडियो द्वारा बैकग्राउंड हटाएं और व्हाइट शैडो जोड़ें।',
    camera_guide_saree: 'वस्त्र/साड़ी को समतल फैलाकर केंद्र में रखें',
    camera_guide_pottery: 'शिल्प या बर्तन को साफ़ पृष्ठभूमि पर रखें',
    camera_guide_craft: 'हस्तशिल्प को फ्रेम के बीच में रखें',
    btn_take_photo: 'फोटो खींचें',
    btn_retake: 'दोबारा लें',
    btn_gallery: 'गैलरी से चुनें',
    btn_enhance_ai: 'एआई द्वारा फोटो साफ़ करें',
    enhancing_image: 'एआई स्टूडियो बैकग्राउंड हटा रहा है...',
    compare_raw: 'मूल फोटो',
    compare_studio: 'एआई स्टूडियो फोटो',
    drag_to_compare: 'तुलना करने के लिए स्लाइडर खींचें',
    guide_craft: 'सामान्य शिल्प',
    guide_saree: 'साड़ी एवं वस्त्र',
    guide_pottery: 'बर्तन एवं मूर्ति',
    compressing_image: 'ग्रामीण नेटवर्क हेतु फोटो का आकार (≤2MB) अनुकूलित हो रहा है...',
    gallery_permission_denied: 'फोटो चुनने के लिए गैलरी की अनुमति आवश्यक है।',
    camera_permission_denied: 'हस्तशिल्प फोटो खींचने के लिए कैमरा अनुमति आवश्यक है।',

    // Voice Cataloging
    voice_title: 'अपनी भाषा में बोलें',
    voice_sub: 'माइक दबाकर रखें और उत्पाद के बारे में बताएं (सामग्री, बनाने का समय, लागत)',
    voice_example_prompt: 'जैसे: "यह बनारसी सिल्क साड़ी है, 12 दिन में तैयार हुई, लागत ₹2,500 है"',
    hold_to_talk: 'बोलने के लिए दबाकर रखें',
    recording_active: 'आवाज़ रिकॉर्ड हो रही है... छोड़ें जब पूरा हो',
    voice_processing: 'एआई आपकी आवाज़ समझ रहा है...',
    voice_retry: 'दोबारा बोलें',
    error_mic_permission: 'माइक्रोफ़ोन अनुमति आवश्यक है। कृपया सेटिंग्स में माइक्रोफ़ोन की अनुमति दें।',
    error_voice_pipeline: 'आवाज़ विश्लेषण में समस्या आई। कृपया सर्वर कनेक्शन जांचें और पुनः प्रयास करें।',
    error_no_audio: 'आवाज़ रिकॉर्ड नहीं हुई। कृपया माइक दबाकर साफ़ बोलें।',
    voice_required_prompt: 'समीक्षा करने से पहले कृपया आवाज़ से उत्पाद का विवरण रिकॉर्ड करें।',
    audio_listen: 'सुनें',

    // Attribute Review Cards
    attr_craft_category: 'शिल्प श्रेणी',
    attr_material: 'सामग्री एवं बुनाई',
    attr_labor_days: 'बनाने में लगे दिन',
    attr_cost_price: 'लागत मूल्य (INR)',
    attr_title_en: 'अंग्रेजी शीर्षक',
    attr_title_hi: 'हिंदी शीर्षक',
    attr_desc_en: 'अंग्रेजी विवरण',
    attr_desc_hi: 'हिंदी विवरण',
    attr_edit: 'संपादित करें',
    attr_save: 'सहेजें',
    label_regional_lang: 'हिंदी / क्षेत्रीय भाषा',
    label_english: 'अंग्रेजी (English)',
    days_unit: 'दिन',
    section_sales_channels: 'विक्रय चैनल एवं मूल्य निर्धारण',
    section_logistics_pkg: 'पार्सल वजन एवं डिब्बा',
    fragile_sub: 'डाकघर द्वारा पार्सल पर FRAGILE / संभलकर ले जाएं लेबल लगाया जाएगा।',
    btn_delete: 'हटाएं',
    save_changes: 'चैनल एवं मूल्य परिवर्तन सहेजें',
    saving_changes: 'बदलाव सहेजे जा रहे हैं...',
    product_updated_success: 'उत्पाद विवरण सफलतापूर्वक अपडेट किया गया!',
    product_update_error: 'उत्पाद अपडेट करने में त्रुटि हुई। कृपया पुनः प्रयास करें।',

    // Omnichannel Pricing & Logistics
    channel_d2c_title: 'घरेलू खुदरा (D2C)',
    channel_d2c_sub: 'स्थानीय खुदरा ग्राहकों के लिए विक्रय मूल्य',
    channel_b2b_title: 'घरेलू थोक (B2B Bulk)',
    channel_b2b_sub: 'थोक विक्रेताओं के लिए रियायती मूल्य एवं न्यूनतम मात्रा',
    channel_export_title: 'डीएनके वैश्विक निर्यात (Global Export)',
    channel_export_sub: 'अंतरराष्ट्रीय ग्राहकों के लिए डॉलर (USD) मूल्य',
    moq_label: 'न्यूनतम ऑर्डर मात्रा (MOQ)',
    export_viable_approved: 'निर्यात हेतु अनुपालन स्वीकृत',
    export_viable_warning: 'कस्टम्स अनुपालन समीक्षा आवश्यक',
    pkg_weight: 'पार्सल का वजन (ग्राम)',
    pkg_box_size: 'मानक डिब्बा आकार',
    is_fragile: 'नाजुक वस्तु (Fragile / टूटने योग्य)',
    btn_publish: 'उत्पाद प्रकाशित करें',
    publishing: 'उत्पाद प्रकाशित हो रहा है...',
    publish_success: 'उत्पाद सफलतापूर्वक प्रकाशित हो गया!',
    draft_saved_local: 'ड्राफ्ट इस डिवाइस पर सुरक्षित है (ऑफ़लाइन)',

    // Orders & Postal QR
    orders_title: 'ऑर्डर एवं डाक प्रबंधन',
    orders_subtitle: 'अपने घरेलू एवं वैश्विक निर्यात ऑर्डर्स ट्रैक करें और डाकघर QR कोड जनरेट करें।',
    tab_all: 'सभी',
    tab_d2c: 'D2C खुदरा',
    tab_b2b: 'B2B थोक',
    tab_export: 'वैश्विक निर्यात',
    status_pending: 'ड्रॉप-ऑफ बाकी',
    status_dropped: 'डाकघर में जमा',
    status_in_transit: 'मार्ग में (In Transit)',
    status_delivered: 'वितरित (Delivered)',
    btn_show_qr: 'डाक काउंटर QR दिखाएं',
    btn_close_qr: 'QR कोड छिपाएं',
    tracking_unavailable: 'ट्रैकिंग जानकारी अभी उपलब्ध नहीं है',
    qr_title: 'डाक काउंटर स्कैन क्यूआर कोड',
    qr_sub: 'पार्सल जमा करते समय डाकघर काउंटर पर यह क्यूआर दिखाएं',
    tracking_code: 'डाक ट्रैकिंग नंबर',
    btn_print_label: 'CN23 लेबल प्रिंट करें',

    // DNK Dropoff
    dropoff_title: 'निकटतम डाक घर निर्यात केंद्र',
    dropoff_sub: 'पार्सल जमा करने के लिए अपना नजदीकी डाकघर चुनें',
    detecting_location: 'आपकी जीपीएस स्थिति खोजी जा रही है...',
    permission_denied: 'जीपीएस अनुमति आवश्यक है',
    permission_denied_desc: 'स्थान की अनुमति अस्वीकृत है। कृपया सेटिंग्स में जीपीएस चालू करें।',
    gps_status: 'जीपीएस स्थिति',
    btn_retry_gps: 'स्थान पुनः खोजें',
    finding_nearest_centers: 'निकटतम डाकघर निर्यात केंद्र खोजे जा रहे हैं...',
    no_centers_title: 'कोई डाकघर केंद्र नहीं मिला',
    no_centers_sub: 'आपके वर्तमान स्थान के 25 किमी के दायरे में कोई सक्रिय डाक घर निर्यात केंद्र नहीं मिला।',
    label_pincode: 'पिनकोड',
    label_hours: 'कार्य समय',
    label_contact: 'संपर्क',
    open_maps: 'गूगल मैप्स में दिशा देखें',
    distance_km: 'किमी दूर',

    // Common
    logout: 'लॉगआउट',
    logout_confirm: 'क्या आप लॉगआउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    loading: 'लोड हो रहा है...',
    error_connection_title: 'सर्वर कनेक्शन समस्या',
    error_connection: 'सर्वर से संपर्क नहीं हो पा रहा है। कृपया इंटरनेट जांचें।',
  },

  kn: {
    app_title: 'ಡಾಕ್ ಘರ್ ನಿರ್ಯಾತ್ ಕೇಂದ್ರ',
    app_subtitle: 'ಕರಕುಶಲ ರಫ್ತು ಪೋರ್ಟಲ್',
    india_post: 'ಭಾರತೀಯ ಅಂಚೆ',
    dept_posts: 'ಅಂಚೆ ಇಲಾಖೆ, ಸಂವಹನ ಸಚಿವಾಲಯ',
    splash_badge: 'ಭಾರತೀಯ ಅಂಚೆ • ಡಾಕ್ ಘರ್ ನಿರ್ಯಾತ್ ಕೇಂದ್ರ',
    splash_tagline: 'ನಿಮ್ಮ ಕರಕುಶಲತೆಗೆ ಜಾಗತಿಕ ಮಾರುಕಟ್ಟೆ ನೀಡಿ',
    splash_btn_start: 'ಪ್ರಾರಂಭಿಸಿ (Login)',
    splash_pillar_1_title: '1. ಫೋಟೋ ತೆಗೆಯಿರಿ',
    splash_pillar_1_desc: 'ನಿಮ್ಮ ಕರಕುಶಲ ಫೋಟೋ ತೆಗೆಯಿರಿ, ಎಐ ಹಿನ್ನೆಲೆ ಸ್ವಚ್ಛಗೊಳಿಸುತ್ತದೆ.',
    splash_pillar_2_title: '2. ಧ್ವನಿ ವಿವರಣೆ',
    splash_pillar_2_desc: 'ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ, ವಿವರಗಳು ತಾನಾಗಿಯೇ ದಾಖಲಾಗುತ್ತವೆ.',
    splash_pillar_3_title: '3. ಅಂಚೆ ಕಚೇರಿ ಡ್ರಾಪ್-ಆಫ್',
    splash_pillar_3_desc: 'ಹತ್ತಿರದ ಅಂಚೆ ಕಚೇರಿಯಲ್ಲಿ ಪಾರ್ಸಲ್ ನೀಡಿ ಜಾಗತಿಕವಾಗಿ ಕಳುಹಿಸಿ.',
    splash_footer: 'ಸಂವಹನ ಸಚಿವಾಲಯ • ಭಾರತ ಸರ್ಕಾರ • ಡಿಜಿಟಲ್ ಇಂಡಿಯಾ',
    login_title: 'ಕುಶಲಕರ್ಮಿ ಲಾಗಿನ್',
    login_sub: 'ನಿಮ್ಮ ನೋಂದಾಯಿತ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    login_phone_tab: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    login_email_tab: 'ಇಮೇಲ್',
    mobile_num: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    email_addr: 'ಇಮೇಲ್ ವಿಳಾಸ',
    enter_phone: '10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    btn_get_otp: 'ಒಟಿಪಿ ಪಡೆಯಿರಿ',
    sending_otp: 'ಒಟಿಪಿ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    verify_otp_title: 'ಒಟಿಪಿ ಪರಿಶೀಲನೆ',
    verify_otp_sub: 'ನಿಮ್ಮ ಸಂಖ್ಯೆಗೆ ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ',
    otp_code: 'ಒಟಿಪಿ ಕೋಡ್',
    btn_verify: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ',
    verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    resend_otp: 'ಒಟಿಪಿ ಮರುಕಳುಹಿಸಿ',
    resend_in: 'ಮರುಕಳುಹಿಸಿ',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    choose_dialect: 'ಮಾತೃಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    change_number: 'ಸಂಖ್ಯೆ ಬದಲಾಯಿಸಿ',
    invalid_otp: 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 6-ಅಂಕಿಯ ಒಟಿಪಿ ನಮೂದಿಸಿ',
    tab_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    tab_studio: 'ಎಐ ಸ್ಟುಡಿಯೋ',
    tab_orders: 'ಆರ್ಡರ್‌ಗಳು',
    tab_dropoff: 'ಅಂಚೆ ಕಚೇರಿ',
    tab_products: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    greeting_artisan: 'ನಮಸ್ಕಾರ, ಕುಶಲಕರ್ಮಿಗಳೇ',
    kpi_active_products: 'ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
    kpi_total_earnings: 'ಒಟ್ಟು ಗಳಿಕೆ (INR)',
    kpi_pending_dropoff: 'ಬಾಕಿ ಡ್ರಾಪ್-ಆಫ್',
    kpi_market_leads: 'ಮಾರುಕಟ್ಟೆ ಅವಕಾಶಗಳು (Market Opportunities)',
    add_btn: 'ಸೇರಿಸಿ',
    quick_action_add: 'ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ',
    quick_action_dropoff: 'ಹತ್ತಿರದ ಅಂಚೆ ಕಚೇರಿ',
    quick_action_orders: 'ಆರ್ಡರ್ ಮತ್ತು ಲೇಬಲ್‌ಗಳು',
    section_active_catalog: 'ಸಕ್ರಿಯ ಉತ್ಪನ್ನಗಳು',
    section_market_opps: 'ಮಾರುಕಟ್ಟೆ ಬೇಡಿಕೆಗಳು',
    section_recent_orders: 'ಇತ್ತೀಚಿನ ಆರ್ಡರ್‌ಗಳು',
    view_all: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    no_products_title: 'ಇನ್ನೂ ಯಾವುದೇ ಉತ್ಪನ್ನಗಳಿಲ್ಲ',
    no_products_sub: 'ಎಐ ಸ್ಟುಡಿಯೋ ಬಳಸಿ ನಿಮ್ಮ ಮೊದಲ ಕರಕುಶಲ ಉತ್ಪನ್ನವನ್ನು ಸೇರಿಸಿ.',
    no_orders_title: 'ಯಾವುದೇ ಹೊಸ ಆರ್ಡರ್ ಇಲ್ಲ',
    no_orders_sub: 'ಅಂತರರಾಷ್ಟ್ರೀಯ ಖರೀದಿದಾರರು ಆರ್ಡರ್ ಮಾಡಿದಾಗ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    no_opps_title: 'ಯಾವುದೇ ಹೊಸ ಅವಕಾಶಗಳಿಲ್ಲ',
    no_opps_sub: 'ಪ್ರಸ್ತುತ ಯಾವುದೇ ಸಗಟು ಬೇಡಿಕೆಗಳು ಲಭ್ಯವಿಲ್ಲ.',
    btn_retry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    studio_wizard_title: 'ಎಐ ಸ್ಟುಡಿಯೋ ಮತ್ತು ಧ್ವನಿ ಕ್ಯಾಟಲಾಗ್',
    step_camera: '1. ಫೋಟೋ ತೆಗೆಯಿರಿ',
    step_enhance: '2. ಎಐ ಸಂಸ್ಕರಣೆ',
    step_voice: '3. ಧ್ವನಿ ವಿವರಣೆ',
    step_review: '4. ಪರಿಶೀಲನೆ',
    step_pricing: '5. ಬೆಲೆ ಮತ್ತು ಚಾನೆಲ್',
    camera_step_sub: 'ನಿಮ್ಮ ಕರಕುಶಲತೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ. ಮಧ್ಯದಲ್ಲಿರಿಸಿ.',
    enhance_step_sub: 'ಎಐ ಮೂಲಕ ಹಿನ್ನೆಲೆ ತೆಗೆದು ಸ್ವಚ್ಛಗೊಳಿಸಿ.',
    camera_guide_saree: 'ವಸ್ತ್ರವನ್ನು ಮಧ್ಯದಲ್ಲಿ ಇರಿಸಿ',
    camera_guide_pottery: 'ಕರಕುಶಲ ವಸ್ತುವನ್ನು ಮಧ್ಯದಲ್ಲಿರಿಸಿ',
    camera_guide_craft: 'ಫ್ರೇಮ್ ಮಧ್ಯದಲ್ಲಿ ವಸ್ತುವನ್ನು ಇರಿಸಿ',
    btn_take_photo: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    btn_retake: 'ಮತ್ತೆ ತೆಗೆಯಿರಿ',
    btn_gallery: 'ಗ್ಯಾಲರಿಯಿಂದ ಆರಿಸಿ',
    btn_enhance_ai: 'ಎಐ ಮೂಲಕ ಸ್ವಚ್ಛಗೊಳಿಸಿ',
    enhancing_image: 'ಹಿನ್ನೆಲೆ ತೆಗೆಯಲಾಗುತ್ತಿದೆ...',
    compare_raw: 'ಮೂಲ ಫೋಟೋ',
    compare_studio: 'ಎಐ ಸ್ಟುಡಿಯೋ ಫೋಟೋ',
    drag_to_compare: 'ಹೋಲಿಸಲು ಸ್ಲೈಡರ್ ಎಳೆಯಿರಿ',
    guide_craft: 'ಸಾಮಾನ್ಯ ಕರಕುಶಲ',
    guide_saree: 'ಸೀರೆ ಮತ್ತು ವಸ್ತ್ರ',
    guide_pottery: 'ಮಣ್ಣಿನ ಪಾತ್ರೆ & ಕರಕುಶಲ',
    compressing_image: 'ಫೋಟೋ ಗಾತ್ರವನ್ನು (≤2MB) ಆಪ್ಟಿಮೈಜ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    gallery_permission_denied: 'ಫೋಟೋಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಗ್ಯಾಲರಿ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
    camera_permission_denied: 'ಫೋಟೋ ತೆಗೆಯಲು ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ.',
    voice_title: 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ',
    voice_sub: 'ಮೈಕ್ ಹಿಡಿದುಕೊಂಡು ಉತ್ಪನ್ನದ ಬಗ್ಗೆ ಮಾತನಾಡಿ (ವಸ್ತು, ಶ್ರಮದ ದಿನಗಳು, ವೆಚ್ಚ)',
    voice_example_prompt: 'ಉದಾ: "ಇದು ಬನಾರಸಿ ರೇಷ್ಮೆ ಸೀರೆ, 12 ದಿನಗಳಲ್ಲಿ ತಯಾರಿಸಲಾಗಿದೆ, ವೆಚ್ಚ ₹2,500."',
    hold_to_talk: 'ಮಾತನಾಡಲು ಒತ್ತಿ ಹಿಡಿಯಿರಿ',
    recording_active: 'ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ...',
    voice_processing: 'ಧ್ವನಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    voice_retry: 'ಮತ್ತೆ ಮಾತನಾಡಿ',
    error_mic_permission: 'ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ. ದಯವಿಟ್ಟು ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಅನುಮತಿಸಿ.',
    error_voice_pipeline: 'ಧ್ವನಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಸರ್ವರ್ ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ.',
    error_no_audio: 'ಯಾವುದೇ ಧ್ವನಿ ದಾಖಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೈಕ್ ಒತ್ತಿ ಮಾತನಾಡಿ.',
    voice_required_prompt: 'ಪರಿಶೀಲಿಸುವ ಮೊದಲು ದಯವಿಟ್ಟು ಧ್ವನಿ ವಿವರಗಳನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ.',
    audio_listen: 'ಕೇಳಿ',
    attr_craft_category: 'ಕರಕುಶಲ ವರ್ಗ',
    attr_material: 'ವಸ್ತು ಮತ್ತು ನೇಯ್ಗೆ',
    attr_labor_days: 'ಶ್ರಮದ ದಿನಗಳು',
    attr_cost_price: 'ಉತ್ಪಾದನಾ ವೆಚ್ಚ (INR)',
    attr_title_en: 'ಇಂಗ್ಲಿಷ್ ಶೀರ್ಷಿಕೆ',
    attr_title_hi: 'ಸ್ಥಳೀಯ ಶೀರ್ಷಿಕೆ',
    attr_desc_en: 'ಇಂಗ್ಲಿಷ್ ವಿವರಣೆ',
    attr_desc_hi: 'ಸ್ಥಳೀಯ ವಿವರಣೆ',
    attr_edit: 'ತಿದ್ದುಪಡಿ',
    attr_save: 'ಉಳಿಸಿ',
    label_regional_lang: 'ಕನ್ನಡ / ಪ್ರಾದೇಶಿಕ ಭಾಷೆ',
    label_english: 'ಇಂಗ್ಲಿಷ್ (English)',
    days_unit: 'ದಿನಗಳು',
    section_sales_channels: 'ಮಾರಾಟ ಚಾನೆಲ್‌ಗಳು ಮತ್ತು ಬೆಲೆ',
    section_logistics_pkg: 'ಪಾರ್ಸಲ್ ತೂಕ ಮತ್ತು ಪ್ಯಾಕೇಜಿಂಗ್',
    fragile_sub: 'ಅಂಚೆ ಕಚೇರಿಯಿಂದ ಪಾರ್ಸಲ್‌ಗೆ FRAGILE ಲೇಬಲ್ ಅಂಟಿಸಲಾಗುತ್ತದೆ.',
    btn_delete: 'ಅಳಿಸಿ',
    save_changes: 'ಬೆಲೆ ಮತ್ತು ಚಾನೆಲ್ ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    saving_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    product_updated_success: 'ಉತ್ಪನ್ನದ ವಿವರಗಳನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    product_update_error: 'ಉತ್ಪನ್ನ ನವೀಕರಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    channel_d2c_title: 'ದೇಶೀಯ ಚಿಲ್ಲರೆ (D2C)',
    channel_d2c_sub: 'ಸ್ಥಳೀಯ ಗ್ರಾಹಕರಿಗೆ ಚಿಲ್ಲರೆ ಬೆಲೆ',
    channel_b2b_title: 'ದೇಶೀಯ ಸಗಟು (B2B Bulk)',
    channel_b2b_sub: 'ಸಗಟು ಗ್ರಾಹಕರಿಗೆ ಬೆಲೆ ಮತ್ತು ಕನಿಷ್ಠ ಪ್ರಮಾಣ',
    channel_export_title: 'ಜಾಗತಿಕ ರಫ್ತು (DNK Export)',
    channel_export_sub: 'ವಿದೇಶಿ ಖರೀದಿದಾರರಿಗೆ ಡಾಲರ್ (USD) ಬೆಲೆ',
    moq_label: 'ಕನಿಷ್ಠ ಆರ್ಡರ್ ಪ್ರಮಾಣ (MOQ)',
    export_viable_approved: 'ರಫ್ತು ಅನುಮೋದನೆ ಪಡೆದಿದೆ',
    export_viable_warning: 'ಕಸ್ಟಮ್ಸ್ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿದೆ',
    pkg_weight: 'ಪಾರ್ಸಲ್ ತೂಕ (ಗ್ರಾಂ)',
    pkg_box_size: 'ಪೆಟ್ಟಿಗೆಯ ಗಾತ್ರ',
    is_fragile: 'ಸೂಕ್ಷ್ಮ ವಸ್ತು (Fragile)',
    btn_publish: 'ಉತ್ಪನ್ನ ಪ್ರಕಟಿಸಿ',
    publishing: 'ಪ್ರಕಟಿಸಲಾಗುತ್ತಿದೆ...',
    publish_success: 'ಉತ್ಪನ್ನ ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕಟಿಸಲಾಗಿದೆ!',
    draft_saved_local: 'ಕರಡು ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ (ಆಫ್‌ಲೈನ್)',
    // Orders & Postal QR
    orders_title: 'ಆರ್ಡರ್‌ಗಳು ಮತ್ತು ಅಂಚೆ ನಿರ್ವಹಣೆ',
    orders_subtitle: 'ನಿಮ್ಮ ದೇಶೀಯ ಮತ್ತು ಜಾಗತಿಕ ರಫ್ತು ಆರ್ಡರ್‌ಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಅಂಚೆ QR ಕೋಡ್ ರಚಿಸಿ.',
    tab_all: 'ಎಲ್ಲವೂ',
    tab_d2c: 'D2C ಚಿಲ್ಲರೆ',
    tab_b2b: 'B2B ಸಗಟು',
    tab_export: 'ಜಾಗತಿಕ ರಫ್ತು',
    status_pending: 'ಡ್ರಾಪ್-ಆಫ್ ಬಾಕಿ',
    status_dropped: 'ಅಂಚೆ ಕಚೇರಿಯಲ್ಲಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
    status_in_transit: 'ಸಾಗಣೆಯಲ್ಲಿದೆ',
    status_delivered: 'ತಲುಪಿಸಲಾಗಿದೆ',
    btn_show_qr: 'ಅಂಚೆ QR ಕೋಡ್ ತೋರಿಸಿ',
    btn_close_qr: 'QR ಕೋಡ್ ಮರೆಮಾಡಿ',
    tracking_unavailable: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ',
    qr_title: 'ಅಂಚೆ ಕೌಂಟರ್ ಸ್ಕ್ಯಾನ್ ಕ್ಯೂಆರ್',
    qr_sub: 'ಅಂಚೆ ಕಚೇರಿಯಲ್ಲಿ ಈ ಕ್ಯೂಆರ್ ಕೋಡ್ ತೋರಿಸಿ',
    tracking_code: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಸಂಖ್ಯೆ',
    btn_print_label: 'CN23 ಲೇಬಲ್ ಮುದ್ರಿಸಿ',
    dropoff_title: 'ಹತ್ತಿರದ ಡಾಕ್ ಘರ್ ನಿರ್ಯಾತ್ ಕೇಂದ್ರ',
    dropoff_sub: 'ಪಾರ್ಸಲ್ ಕಳುಹಿಸಲು ಹತ್ತಿರದ ಅಂಚೆ ಕಚೇರಿ ಆರಿಸಿ',
    detecting_location: 'ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
    permission_denied: 'ಜಿಪಿಎಸ್ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ',
    permission_denied_desc: 'ಸ್ಥಳದ ಅನುಮತಿಯನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಜಿಪಿಎಸ್ ಆನ್ ಮಾಡಿ.',
    gps_status: 'ಜಿಪಿಎಸ್ ಸ್ಥಳ',
    btn_retry_gps: 'ಜಿಪಿಎಸ್ ಮರುಪ್ರಯತ್ನಿಸಿ',
    finding_nearest_centers: 'ಹತ್ತಿರದ ಡಾಕ್ ಘರ್ ನಿರ್ಯಾತ್ ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
    no_centers_title: 'ಯಾವುದೇ ಅಂಚೆ ಕಚೇರಿ ಕೇಂದ್ರ ಕಂಡುಬಂದಿಲ್ಲ',
    no_centers_sub: 'ನಿಮ್ಮ ಸ್ಥಳದಿಂದ 25 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಕೇಂದ್ರಗಳಿಲ್ಲ.',
    label_pincode: 'ಪಿನ್‌ಕೋಡ್',
    label_hours: 'ಕೆಲಸದ ಸಮಯ',
    label_contact: 'ಸಂಪರ್ಕ',
    open_maps: 'ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    distance_km: 'ಕಿ.ಮೀ ದೂರ',
    logout: 'ಲಾಗ್‌ಔಟ್',
    logout_confirm: 'ಖಾತೆಯಿಂದ ನಿರ್ಗಮಿಸಲು ಬಯಸುವಿರಾ?',
    cancel: 'ರದ್ದುಮಾಡಿ',
    confirm: 'ದೃಢೀಕರಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    error_connection_title: 'ಸರ್ವರ್ ಸಂಪರ್ಕ ಸಮಸ್ಯೆ',
    error_connection: 'ಸರ್ವರ್ ಸಂಪರ್ಕ ಸಾಧ್ಯವಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಪರಿಶೀಲಿಸಿ.',
  },

  ta: {
    app_title: 'டாக் கர் நிர்யாத் கேந்திரா',
    app_subtitle: 'கைவினைஞர் ஏற்றுமதி தளம்',
    india_post: 'இந்திய அஞ்சல்',
    dept_posts: 'அஞ்சல் துறை, தகவல் தொடர்பு அமைச்சகம்',
    splash_badge: 'இந்திய அஞ்சல் • டாக் கர் நிர்யாத் கேந்திரா',
    splash_tagline: 'உங்கள் கைவினைப் பொருட்களுக்கு உலகளாவிய சந்தை',
    splash_btn_start: 'தொடங்கவும் (Login)',
    splash_pillar_1_title: '1. புகைப்படம் எடு',
    splash_pillar_1_desc: 'கைவினைப் பொருளை படம் எடுக்கவும், AI பின்னணியை நீக்கும்.',
    splash_pillar_2_title: '2. குரல் விளக்கம்',
    splash_pillar_2_desc: 'உங்கள் தாய்மொழியில் பேசுங்கள், விவரங்கள் தானாகப் பதிவாகும்.',
    splash_pillar_3_title: '3. அஞ்சலக ஒப்படைப்பு',
    splash_pillar_3_desc: 'அருகிலுள்ள அஞ்சலகத்தில் பார்சலை ஒப்படைத்து உலகளவில் அனுப்பவும்.',
    splash_footer: 'தகவல் தொடர்பு அமைச்சகம் • இந்திய அரசு • டிஜிட்டல் இந்தியா',
    login_title: 'கைவினைஞர் உள்நுழைவு',
    login_sub: 'பதிவு செய்யப்பட்ட கைபேசி எண்ணை உள்ளிடவும்',
    login_phone_tab: 'கைபேசி எண்',
    login_email_tab: 'மின்னஞ்சல்',
    mobile_num: 'கைபேசி எண்',
    email_addr: 'மின்னஞ்சல் முகவரி',
    enter_phone: '10 இலக்க கைபேசி எண்',
    btn_get_otp: 'OTP பெறவும்',
    sending_otp: 'OTP அனுப்பப்படுகிறது...',
    verify_otp_title: 'OTP சரிபார்ப்பு',
    verify_otp_sub: 'அனுப்பப்பட்ட 6-இலக்க குறியீட்டை உள்ளிடவும்',
    otp_code: 'OTP குறியீடு',
    btn_verify: 'சரிபார்த்து தொடரவும்',
    verifying: 'சரிபார்க்கிறது...',
    resend_otp: 'OTP மீண்டும் அனுப்பு',
    resend_in: 'மீண்டும் அனுப்ப',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    choose_dialect: 'தாய்மொழியைத் தேர்ந்தெடுக்கவும்',
    change_number: 'எண் மாற்றவும்',
    invalid_otp: 'சரியான 6-இலக்க OTP உள்ளிடவும்',
    tab_dashboard: 'முகப்பு',
    tab_studio: 'AI ஸ்டுடியோ',
    tab_orders: 'ஆர்டர்கள்',
    tab_dropoff: 'அஞ்சலகம்',
    tab_products: 'என் பொருட்கள்',
    greeting_artisan: 'வணக்கம், கைவினைஞரே',
    kpi_active_products: 'செயலில் உள்ள பொருட்கள்',
    kpi_total_earnings: 'மொத்த வருவாய் (INR)',
    kpi_pending_dropoff: 'நிலுவையில் உள்ள ஒப்படைப்பு',
    kpi_market_leads: 'சந்தை வாய்ப்புகள் (Market Opportunities)',
    add_btn: 'சேர்க்க',
    quick_action_add: 'புதிய பொருள் சேர்க்க',
    quick_action_dropoff: 'அருகிலுள்ள அஞ்சலகம்',
    quick_action_orders: 'ஆர்டர்கள் மற்றும் லேபிள்கள்',
    section_active_catalog: 'பொருட்கள் பட்டியல்',
    section_market_opps: 'சந்தை தேவைகள்',
    section_recent_orders: 'சமீபத்திய ஆர்டர்கள்',
    view_all: 'அனைத்தும் பார்க்க',
    no_products_title: 'பொருட்கள் இல்லை',
    no_products_sub: 'AI ஸ்டுடியோ மூலம் உங்கள் முதல் கைவினைப் பொருளைச் சேர்க்கவும்.',
    no_orders_title: 'புதிய ஆர்டர்கள் இல்லை',
    no_orders_sub: 'சர்வதேச வாங்குபவர்கள் வாங்கும் போது இங்கு தோன்றும்.',
    no_opps_title: 'புதிய வாய்ப்புகள் இல்லை',
    no_opps_sub: 'தற்போது புதிய மொத்த தேவைகள் இல்லை.',
    btn_retry: 'மீண்டும் முயற்சிக்கவும்',
    studio_wizard_title: 'AI ஸ்டுடியோ & குரல் பட்டியல்',
    step_camera: '1. புகைப்படம் எடு',
    step_enhance: '2. AI மேம்பாடு',
    step_voice: '3. குரல் விளக்கம்',
    step_review: '4. மதிப்பாய்வு',
    step_pricing: '5. விலை நிர்ணயம்',
    camera_step_sub: 'உங்கள் கைவினைப் பொருளின் தெளிவான படத்தை எடுக்கவும்.',
    enhance_step_sub: 'AI பின்னணியை நீக்கி மெருகூட்டுகிறது.',
    camera_guide_saree: 'ஆடையை மையத்தில் வைக்கவும்',
    camera_guide_pottery: 'பொருளை மையத்தில் வைக்கவும்',
    camera_guide_craft: 'கைவினைப் பொருளை மையத்தில் வைக்கவும்',
    btn_take_photo: 'படம் எடுக்கவும்',
    btn_retake: 'மீண்டும் எடுக்கவும்',
    btn_gallery: 'கேலரியில் தேர்ந்தெடுக்க',
    btn_enhance_ai: 'AI மூலம் மெருகூட்டவும்',
    enhancing_image: 'பின்னணி நீக்கப்படுகிறது...',
    compare_raw: 'அசல் புகைப்படம்',
    compare_studio: 'AI ஸ்டுடியோ படம்',
    drag_to_compare: 'ஒப்பிட ஸ்லைடரை இழுக்கவும்',
    guide_craft: 'பொது கைவினை',
    guide_saree: 'புடவை & ஜவுளி',
    guide_pottery: 'மண்பாண்டம் & களிமண்',
    compressing_image: 'புகைப்படத்தின் அளவு (≤2MB) உகந்ததாக்கப்படுகிறது...',
    gallery_permission_denied: 'புகைப்படங்களைத் தேர்ந்தெடுக்க கேலரி அனுமதி தேவை.',
    camera_permission_denied: 'படம் எடுக்க கேமரா அனுமதி தேவை.',
    voice_title: 'உங்கள் மொழியில் பேசுங்கள்',
    voice_sub: 'மைக்கை அழுத்திப் பிடித்து பொருளைப் பற்றி விவரிக்கவும்',
    voice_example_prompt: 'எ.கா: "இது பனாரசி பட்டுப் புடவை, 12 நாட்களில் தயாரிக்கப்பட்டது, அடக்க விலை ₹2,500."',
    hold_to_talk: 'பேச அழுத்திப் பிடிக்கவும்',
    recording_active: 'பதிவாகிறது...',
    voice_processing: 'குரல் செயலாக்கப்படுகிறது...',
    voice_retry: 'மீண்டும் பேசவும்',
    error_mic_permission: 'மைக்ரோஃபோன் அனுமதி தேவை. அமைப்புகளில் மைக்ரோஃபோனை இயக்கவும்.',
    error_voice_pipeline: 'குரல் விவரங்களை செயலாக்க முடியவில்லை. சேவையக இணைப்பைச் சரிபார்க்கவும்.',
    error_no_audio: 'ஆடியோ பதிவு செய்யப்படவில்லை. மைக் அழுத்தி தெளிவாகப் பேசவும்.',
    voice_required_prompt: 'மதிப்பாய்வு செய்வதற்கு முன் குரல் விவரங்களை பதிவு செய்யவும்.',
    audio_listen: 'கேட்க',
    attr_craft_category: 'கைவினை வகை',
    attr_material: 'பொருள் & நெசவு',
    attr_labor_days: 'உழைப்பு நாட்கள்',
    attr_cost_price: 'உற்பத்தி செலவு (INR)',
    attr_title_en: 'ஆங்கில தலைப்பு',
    attr_title_hi: 'உள்ளூர் தலைப்பு',
    attr_desc_en: 'ஆங்கில விளக்கம்',
    attr_desc_hi: 'உள்ளூர் விளக்கம்',
    attr_edit: 'திருத்து',
    attr_save: 'சேமி',
    label_regional_lang: 'தமிழ் / பிராந்திய மொழி',
    label_english: 'ஆங்கிலம் (English)',
    days_unit: 'நாட்கள்',
    section_sales_channels: 'விற்பனை சேனல்கள் & விலை',
    section_logistics_pkg: 'அஞ்சல் எடை & பேக்கேஜிங்',
    fragile_sub: 'அஞ்சலகத்தால் இந்த பார்சலில் FRAGILE லேபிள் ஒட்டப்படும்.',
    btn_delete: 'நீக்கு',
    save_changes: 'விலை மற்றும் சேனல் மாற்றங்களைச் சேமிக்கவும்',
    saving_changes: 'மாற்றங்கள் சேமிக்கப்படுகின்றன...',
    product_updated_success: 'பொருள் விவரங்கள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன!',
    product_update_error: 'பொருளைப் புதுப்பிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    channel_d2c_title: 'உள்நாட்டு சில்லறை (D2C)',
    channel_d2c_sub: 'சில்லறை விற்பனை விலை',
    channel_b2b_title: 'உள்நாட்டு மொத்த விற்பனை (B2B)',
    channel_b2b_sub: 'மொத்த விற்பனை விலை & குறைந்தபட்ச அளவு',
    channel_export_title: 'DNK உலகளாவிய ஏற்றுமதி',
    channel_export_sub: 'டாலர் (USD) விலை',
    moq_label: 'குறைந்தபட்ச அளவு (MOQ)',
    export_viable_approved: 'ஏற்றுமதிக்கு அனுமதிக்கப்பட்டது',
    export_viable_warning: 'சுங்க மதிப்பாய்வு தேவை',
    pkg_weight: 'எடை (கிராம்)',
    pkg_box_size: 'பெட்டி அளவு',
    is_fragile: 'உடையக்கூடிய பொருள் (Fragile)',
    btn_publish: 'பொருளை வெளியிடு',
    publishing: 'வெளியிடப்படுகிறது...',
    publish_success: 'வெற்றிகரமாக வெளியிடப்பட்டது!',
    draft_saved_local: 'வரைவு சேமிக்கப்பட்டது (ஆஃப்லைன்)',
    // Orders & Postal QR
    orders_title: 'ஆர்டர்கள் மற்றும் அஞ்சல் கண்காணிப்பு',
    orders_subtitle: 'உள்நாட்டு மற்றும் உலகளாவிய ஏற்றுமதி ஆர்டர்களைக் கண்காணித்து அஞ்சல் QR குறியீட்டை உருவாக்கவும்.',
    tab_all: 'அனைத்தும்',
    tab_d2c: 'D2C சில்லறை',
    tab_b2b: 'B2B மொத்த',
    tab_export: 'ஏற்றுமதி',
    status_pending: 'ஒப்படைப்பு நிலுவை',
    status_dropped: 'அஞ்சலகத்தில் பெறப்பட்டது',
    status_in_transit: 'வழியில் உள்ளது',
    status_delivered: 'விநியோகிக்கப்பட்டது',
    btn_show_qr: 'அஞ்சல் QR குறியீட்டைக் காட்டு',
    btn_close_qr: 'QR குறியீட்டை மறை',
    tracking_unavailable: 'கண்காணிப்பு தகவல் கிடைக்கவில்லை',
    qr_title: 'அஞ்சல் கவுண்டர் QR குறியீடு',
    qr_sub: 'அஞ்சலகத்தில் இந்த QR குறியீட்டைக் காட்டவும்',
    tracking_code: 'கண்காணிப்பு எண்',
    btn_print_label: 'CN23 லேபிள் அச்சிடுக',
    dropoff_title: 'அருகிலுள்ள டாக் கர் நிர்யாத் கேந்திரா',
    dropoff_sub: 'பார்சல் அனுப்ப அருகிலுள்ள அஞ்சலகத்தை தேர்வு செய்யவும்',
    detecting_location: 'இருப்பிடம் கண்டறியப்படுகிறது...',
    permission_denied: 'GPS அனுமதி தேவை',
    permission_denied_desc: 'இருப்பிட அனுமதி மறுக்கப்பட்டது. அமைப்புகளில் GPS-ஐ இயக்கவும்.',
    gps_status: 'GPS இருப்பிடம்',
    btn_retry_gps: 'GPS-ஐ மீண்டும் முயற்சிக்கவும்',
    finding_nearest_centers: 'அருகிலுள்ள டாக் கர் நிர்யாத் கேந்திராக்கள் தேடப்படுகின்றன...',
    no_centers_title: 'அஞ்சலக மையம் எதுவும் கிடைக்கவில்லை',
    no_centers_sub: 'உங்கள் இருப்பிடத்தின் 25 கி.மீ சுற்றளவில் செயலில் உள்ள மையங்கள் எதுவும் இல்லை.',
    label_pincode: 'அஞ்சல் குறியீடு',
    label_hours: 'வேலை நேரம்',
    label_contact: 'தொடர்பு',
    open_maps: 'கூகுள் வரைபடத்தில் பார்க்க',
    distance_km: 'கி.மீ தொலைவு',
    logout: 'வெளியேறு',
    logout_confirm: 'வெளியேற விரும்புகிறீர்களா?',
    cancel: 'ரத்து',
    confirm: 'உறுதி செய்',
    loading: 'ஏற்றுகிறது...',
    error_connection_title: 'சேவையக இணைப்பு சிக்கல்',
    error_connection: 'இணைக்க முடியவில்லை. இணையத்தை சரிபார்க்கவும்.',
  },

  bn: {
    app_title: 'ডাক ঘর রফতানি কেন্দ্র',
    app_subtitle: 'কারিগর রফতানি পোর্টাল',
    india_post: 'ভারতীয় ডাক',
    dept_posts: 'ডাক বিভাগ, যোগাযোগ মন্ত্রক',
    splash_badge: 'ভারতীয় ডাক • ডাক ঘর রফতানি কেন্দ্র',
    splash_tagline: 'আপনার হস্তশিল্পকে দিন বিশ্বব্যাপী বাজার',
    splash_btn_start: 'শুরু করুন (Login)',
    splash_pillar_1_title: '১. ছবি তুলুন',
    splash_pillar_1_desc: 'আপনার পণ্যের ছবি তুলুন, এআই ব্যাকগ্রাউন্ড পরিষ্কার করবে।',
    splash_pillar_2_title: '২. মুখে বলুন',
    splash_pillar_2_desc: 'নিজের ভাষায় বলুন, প্রযুক্তিগত বিবরণ স্বয়ংক্রিয়ভাবে যুক্ত হবে।',
    splash_pillar_3_title: '৩. ডাকঘর ড্রপ-অফ',
    splash_pillar_3_desc: 'নিকটবর্তী ডাকঘরে পার্সেল জমা দিয়ে আন্তর্জাতিক ক্রেতাদের কাছে পাঠান।',
    splash_footer: 'যোগাযোগ মন্ত্রক • ভারত সরকার • ডিজিটাল ইন্ডিয়া',
    login_title: 'কারিগর লগইন',
    login_sub: 'আপনার নিবন্ধিত মোবাইল নম্বর দিন',
    login_phone_tab: 'মোবাইল নম্বর',
    login_email_tab: 'ইমেল',
    mobile_num: 'মোবাইল নম্বর',
    email_addr: 'ইমেল ঠিকানা',
    enter_phone: '১০ অঙ্কের মোবাইল নম্বর',
    btn_get_otp: 'ওটিপি পান',
    sending_otp: 'ওটিপি পাঠানো হচ্ছে...',
    verify_otp_title: 'ওটিপি যাচাইকরণ',
    verify_otp_sub: 'আপনার নম্বরে প্রেরিত ৬-অঙ্কের কোড লিখুন',
    otp_code: 'ওটিপি কোড',
    btn_verify: 'যাচাই করে এগিয়ে যান',
    verifying: 'যাচাই করা হচ্ছে...',
    resend_otp: 'ওটিপি পুনরায় পাঠান',
    resend_in: 'পুনরায় পাঠান',
    select_language: 'ভাষা নির্বাচন করুন',
    choose_dialect: 'মাতৃভাষা নির্বাচন করুন',
    change_number: 'নম্বর পরিবর্তন',
    invalid_otp: 'দয়া করে সঠিক ৬-অঙ্কের ওটিপি দিন',
    tab_dashboard: 'ড্যাশবোর্ড',
    tab_studio: 'এআই স্টুডিও',
    tab_orders: 'অর্ডার',
    tab_dropoff: 'ডাকঘর ড্রপ-অফ',
    tab_products: 'আমার পণ্য',
    greeting_artisan: 'নমস্কার, শিল্পী মহাশয়',
    kpi_active_products: 'সক্রিয় পণ্য',
    kpi_total_earnings: 'মোট আয় (INR)',
    kpi_pending_dropoff: 'ড্রপ-অফ বাকি',
    kpi_market_leads: 'বাজার সুযোগ (Market Opportunities)',
    add_btn: 'যোগ করুন',
    quick_action_add: 'নতুন পণ্য যোগ করুন',
    quick_action_dropoff: 'নিকটবর্তী ডাকঘর',
    quick_action_orders: 'অর্ডার ও লেবেল',
    section_active_catalog: 'সক্রিয় পণ্যের তালিকা',
    section_market_opps: 'বাজার চাহিদা (Opportunities)',
    section_recent_orders: 'সাম্প্রতিক অর্ডার',
    view_all: 'সব দেখুন',
    no_products_title: 'এখনও কোনো পণ্য নেই',
    no_products_sub: 'এআই স্টুডিও দিয়ে আপনার প্রথম হস্তশিল্প পণ্য যোগ করুন।',
    no_orders_title: 'কোনো নতুন অর্ডার নেই',
    no_orders_sub: 'বিদেশি ক্রেতারা পণ্য কিনলে এখানে দেখা যাবে।',
    no_opps_title: 'কোনো নতুন সুযোগ নেই',
    no_opps_sub: 'বর্তমানে কোনো নতুন পাইকারি চাহিদা নেই।',
    btn_retry: 'আবার চেষ্টা করুন',
    studio_wizard_title: 'এআই স্টুডিও ও ভয়েস ক্যাটালগ',
    step_camera: '১. ছবি তুলুন',
    step_enhance: '২. এআই সম্পাদনা',
    step_voice: '৩. মুখে বলুন',
    step_review: '৪. পর্যালোচনা',
    step_pricing: '৫. মূল্য ও চ্যানেল',
    camera_step_sub: 'আপনার পণ্যের একটি পরিষ্কার ছবি তুলুন। মাঝে রাখুন।',
    enhance_step_sub: 'এআই ব্যাকগ্রাউন্ড সরিয়ে ছবি পরিচ্ছন্ন করে।',
    camera_guide_saree: 'বস্ত্রটিকে মাঝে রাখুন',
    camera_guide_pottery: 'শিল্পকর্মটি মাঝে রাখুন',
    camera_guide_craft: 'পণ্যটিকে ফ্রেমের মাঝে রাখুন',
    btn_take_photo: 'ছবি তুলুন',
    btn_retake: 'আবার তুলুন',
    btn_gallery: 'গ্যালারি থেকে নিন',
    btn_enhance_ai: 'এআই দিয়ে পরিচ্ছন্ন করুন',
    enhancing_image: 'ব্যাকগ্রাউন্ড সরানো হচ্ছে...',
    compare_raw: 'আসল ছবি',
    compare_studio: 'এআই স্টুডিও ছবি',
    drag_to_compare: 'তুলনা করতে স্লাইডার টানুন',
    voice_title: 'নিজের ভাষায় বলুন',
    voice_sub: 'মাইক চেপে ধরে পণ্যের বিবরণ দিন (উপাদান, দিন, খরচ)',
    voice_example_prompt: 'যেমন: "এটি বেনারসি সিল্ক শাড়ি, ১২ দিনে তৈরি হয়েছে, উৎপাদন খরচ ₹২,৫০০"',
    hold_to_talk: 'বলতে চেপে ধরুন',
    recording_active: 'রেকর্ড হচ্ছে...',
    voice_processing: 'এআই আপনার কথা বিশ্লেষণ করছে...',
    voice_retry: 'আবার বলুন',
    error_mic_permission: 'মাইক্রোফোন অনুমতি প্রয়োজন। অনুগ্রহ করে সেটিংসে মাইক্রোফোন সক্রিয় করুন।',
    error_voice_pipeline: 'ভয়েস বিবরণ প্রক্রিয়া করা যায়নি। অনুগ্রহ করে সার্ভার সংযোগ পরীক্ষা করুন।',
    error_no_audio: 'কোনো ভয়েস রেকর্ড হয়নি। অনুগ্রহ করে মাইক চেপে পরিষ্কারভাবে বলুন।',
    voice_required_prompt: 'পর্যালোচনা করার আগে অনুগ্রহ করে ভয়েস বিবরণ রেকর্ড করুন।',
    audio_listen: 'শুনুন',
    attr_craft_category: 'শিল্প বিভাগ',
    attr_material: 'উপাদান ও বুনন',
    attr_labor_days: 'শ্রমের দিন',
    attr_cost_price: 'উৎপাদন খরচ (INR)',
    attr_title_en: 'ইংরেজি নাম',
    attr_title_hi: 'স্থানীয় নাম',
    attr_desc_en: 'ইংরেজি বিবরণ',
    attr_desc_hi: 'স্থানীয় বিবরণ',
    attr_edit: 'সম্পাদনা',
    attr_save: 'সংরক্ষণ',
    label_regional_lang: 'বাংলা / আঞ্চলিক ভাষা',
    label_english: 'ইংরেজি (English)',
    days_unit: 'দিন',
    section_sales_channels: 'বিক্রয় চ্যানেল ও মূল্য নির্ধারণ',
    section_logistics_pkg: 'পার্সেল ওজন ও প্যাকেজিং',
    fragile_sub: 'ডাকঘর দ্বারা পার্সেলে FRAGILE লেবেল লাগানো হবে।',
    btn_delete: 'মুছুন',
    save_changes: 'মূল্য ও চ্যানেল পরিবর্তন সংরক্ষণ করুন',
    saving_changes: 'পরিবর্তন সংরক্ষণ করা হচ্ছে...',
    product_updated_success: 'পণ্যের বিবরণ সফলভাবে আপডেট করা হয়েছে!',
    product_update_error: 'পণ্য আপডেট করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    channel_d2c_title: 'স্থানীয় খুচরা (D2C)',
    channel_d2c_sub: 'খুচরা গ্রাহকদের জন্য বিক্রয়মূল্য',
    channel_b2b_title: 'পাইকারি বিক্রয় (B2B)',
    channel_b2b_sub: 'পাইকারি মূল্য ও সর্বনিম্ন পরিমাণ',
    channel_export_title: 'DNK বিশ্বব্যাপী রফতানি',
    channel_export_sub: 'ডলার (USD) মূল্য',
    moq_label: 'সর্বনিম্ন অর্ডার পরিমাণ (MOQ)',
    export_viable_approved: 'রফতানির জন্য অনুমোদিত',
    export_viable_warning: 'কাস্টমস পর্যালোচনা প্রয়োজন',
    pkg_weight: 'ওজন (গ্রাম)',
    pkg_box_size: 'বাক্সের আকার',
    is_fragile: 'ভঙ্গুর সামগ্রী (Fragile)',
    btn_publish: 'পণ্য প্রকাশ করুন',
    publishing: 'প্রকাশিত হচ্ছে...',
    publish_success: 'সফলভাবে প্রকাশিত হয়েছে!',
    draft_saved_local: 'খসড়া সংরক্ষিত আছে (অফলাইন)',
    // Orders & Postal QR
    orders_title: 'অর্ডার ও ডাক ব্যবস্থাপনা',
    orders_subtitle: 'আপনার দেশীয় ও আন্তর্জাতিক রফতানি অর্ডার ট্র্যাক করুন এবং ডাকঘর QR কোড তৈরি করুন।',
    tab_all: 'সব',
    tab_d2c: 'D2C খুচরা',
    tab_b2b: 'B2B পাইকারি',
    tab_export: 'রফতানি',
    status_pending: 'ড্রপ-অফ বাকি',
    status_dropped: 'ডাকঘরে জমা হয়েছে',
    status_in_transit: 'পথে রয়েছে',
    status_delivered: 'পৌঁছে গেছে',
    btn_show_qr: 'ডাকঘর কিউআর কোড দেখান',
    btn_close_qr: 'কিউআর কোড লুকান',
    tracking_unavailable: 'ট্র্যাকিং তথ্য এখনও উপলব্ধ নেই',
    qr_title: 'ডাক কাউন্টার স্ক্যান কিউআর',
    qr_sub: 'ডাকঘরে এই কিউআর কোডটি দেখান',
    tracking_code: 'ট্র্যাকিং নম্বর',
    btn_print_label: 'CN23 লেবেল প্রিন্ট করুন',
    dropoff_title: 'নিকটবর্তী ডাক ঘর রফতানি কেন্দ্র',
    dropoff_sub: 'পার্সেল জমা দিতে নিকটবর্তী ডাকঘর বাছুন',
    detecting_location: 'অবস্থান খোঁজা হচ্ছে...',
    permission_denied: 'জিপিএস অনুমতি প্রয়োজন',
    permission_denied_desc: 'অবস্থানের অনুমতি প্রত্যাখ্যান করা হয়েছে। অনুগ্রহ করে সেটিংসে জিপিএস সক্রিয় করুন।',
    gps_status: 'জিপিএস অবস্থান',
    btn_retry_gps: 'জিপিএস পুনরায় চেষ্টা করুন',
    finding_nearest_centers: 'নিকটবর্তী ডাক ঘর রফতানি কেন্দ্র খোঁজা হচ্ছে...',
    no_centers_title: 'কোনো ডাকঘর কেন্দ্র পাওয়া যায়নি',
    no_centers_sub: 'আপনার বর্তমান অবস্থানের ২৫ কিমির মধ্যে কোনো সক্রিয় কেন্দ্র পাওয়া যায়নি।',
    label_pincode: 'পিনকোড',
    label_hours: 'কাজের সময়',
    label_contact: 'যোগাযোগ',
    open_maps: 'গুগল ম্যাপে দেখুন',
    distance_km: 'কিমি দূরে',
    logout: 'লগআউট',
    logout_confirm: 'আপনি কি লগআউট করতে চান?',
    cancel: 'বাতিল',
    confirm: 'নিশ্চিত করুন',
    loading: 'লোড হচ্ছে...',
    error_connection_title: 'সার্ভার সংযোগ সমস্যা',
    error_connection: 'সার্ভারের সাথে সংযোগ করা যাচ্ছে না। অনুগ্রহ করে ইন্টারনেট পরীক্ষা করুন।',
  },

  en: {
    app_title: 'Dak Ghar Niryat Kendra',
    app_subtitle: 'Artisan Export Portal',
    india_post: 'India Post',
    dept_posts: 'Department of Posts, Ministry of Communications',
    splash_badge: 'INDIA POST • DAK GHAR NIRYAT KENDRA',
    splash_tagline: 'Give Your Craft Global Market Reach',
    splash_btn_start: 'Get Started (Login)',
    splash_pillar_1_title: '1. Photo Capture',
    splash_pillar_1_desc: 'Capture your craft; AI Studio automatically removes background and enhances lighting.',
    splash_pillar_2_title: '2. Voice Details',
    splash_pillar_2_desc: 'Speak in your native dialect; title and technical specifications are auto-extracted.',
    splash_pillar_3_title: '3. DNK Drop-off',
    splash_pillar_3_desc: 'Drop off parcels at your nearest DNK counter for global export.',
    splash_footer: 'Ministry of Communications • Government of India • Digital India',
    login_title: 'Artisan Login',
    login_sub: 'Enter your registered mobile number to continue',
    login_phone_tab: 'Mobile Number',
    login_email_tab: 'Email',
    mobile_num: 'Mobile Number',
    email_addr: 'Email Address',
    enter_phone: '10-digit mobile number',
    btn_get_otp: 'Send OTP',
    sending_otp: 'Sending OTP...',
    verify_otp_title: 'Verify OTP',
    verify_otp_sub: 'Enter the 6-digit code sent to your registered number',
    otp_code: 'OTP Code',
    btn_verify: 'Verify & Proceed',
    verifying: 'Verifying OTP...',
    resend_otp: 'Resend OTP',
    resend_in: 'Resend in',
    change_number: 'Change Number',
    invalid_otp: 'Please enter a valid 6-digit OTP code',
    tab_dashboard: 'Dashboard',
    tab_studio: 'AI Studio',
    tab_orders: 'Orders & QR',
    tab_dropoff: 'DNK Drop-off',
    tab_products: 'My Products',
    greeting_artisan: 'Welcome, Master Artisan',
    kpi_active_products: 'Active Products',
    kpi_total_earnings: 'Total Earnings (INR)',
    kpi_pending_dropoff: 'Pending Drop-offs',
    kpi_market_leads: 'Market Opportunities',
    add_btn: 'Add',
    quick_action_add: 'Add New Product',
    quick_action_dropoff: 'Locate Nearest DNK',
    quick_action_orders: 'Orders & Labels',
    section_active_catalog: 'Active Catalog',
    section_market_opps: 'SIH26090 Market Opportunities',
    section_recent_orders: 'Recent Orders',
    view_all: 'View All',
    no_products_title: 'No products yet',
    no_products_sub: 'Use the AI Studio to onboard your first handcrafted craft item.',
    no_orders_title: 'No orders yet',
    no_orders_sub: 'When global buyers purchase your items, postal dispatch labels will appear here.',
    no_opps_title: 'No active opportunities',
    no_opps_sub: 'No bulk wholesale buyer requirements match your crafts right now.',
    btn_retry: 'Retry',
    studio_wizard_title: 'AI Studio & Voice Catalog',
    step_camera: '1. Photo Capture',
    step_enhance: '2. AI Studio',
    step_voice: '3. Voice Details',
    step_review: '4. Review Cards',
    step_pricing: '5. Omnichannel Pricing',
    camera_step_sub: 'Capture a clear, well-lit photo of your craft. Keep it centered.',
    enhance_step_sub: 'AI Vision Studio removes the background and synthesizes soft studio shadow.',
    camera_guide_saree: 'Position the textile flat in the center',
    camera_guide_pottery: 'Frame the ceramic or pottery centered',
    camera_guide_craft: 'Place the craft inside the bounding frame',
    btn_take_photo: 'Capture Photo',
    btn_retake: 'Retake',
    btn_gallery: 'Choose from Gallery',
    btn_enhance_ai: 'Enhance with AI Studio',
    enhancing_image: 'AI Studio is removing background & synthesizing shadow...',
    compare_raw: 'Raw Photo',
    compare_studio: 'AI Studio Enhanced',
    drag_to_compare: 'Slide to compare raw vs enhanced',
    guide_craft: 'General Craft',
    guide_saree: 'Saree & Textile',
    guide_pottery: 'Pottery & Clay',
    compressing_image: 'Optimizing photo size (≤2MB) for rural network efficiency...',
    gallery_permission_denied: 'Gallery permission is required to choose photos.',
    camera_permission_denied: 'Camera permission is required to capture craft photos.',
    voice_title: 'Speak in Your Language',
    voice_sub: 'Press and hold the mic button to describe your craft (materials, labor time, cost)',
    voice_example_prompt: 'e.g. "This is a handwoven Banarasi silk saree, crafted in 12 days, base cost is ₹2,500."',
    hold_to_talk: 'Hold to Speak',
    recording_active: 'Recording voice... Release when finished',
    voice_processing: 'AI NLP engine is analyzing your voice...',
    voice_retry: 'Record Again',
    error_mic_permission: 'Microphone permission is required. Please allow microphone access in your browser/device settings.',
    error_voice_pipeline: 'Unable to process voice details. Please check server connection and retry.',
    error_no_audio: 'No audio was captured. Please press and hold the mic while speaking.',
    voice_required_prompt: 'Please record voice details or complete voice extraction before proceeding to review.',
    audio_listen: 'Listen',
    attr_craft_category: 'Craft Category',
    attr_material: 'Material & Weave',
    attr_labor_days: 'Estimated Labor (Days)',
    attr_cost_price: 'Production Cost (INR)',
    attr_title_en: 'English Title',
    attr_title_hi: 'Regional Title',
    attr_desc_en: 'English Description',
    attr_desc_hi: 'Regional Description',
    attr_edit: 'Edit',
    attr_save: 'Save',
    label_regional_lang: 'Regional / Native Dialect',
    label_english: 'English',
    days_unit: 'Days',
    section_sales_channels: 'Sales Channels & Pricing',
    section_logistics_pkg: 'Logistics & Packaging',
    fragile_sub: 'Post office will attach a FRAGILE handle with care sticker to this parcel.',
    btn_delete: 'Delete',
    save_changes: 'Save Channel & Pricing Changes',
    saving_changes: 'Saving Changes...',
    product_updated_success: 'Product details updated successfully!',
    product_update_error: 'Failed to update product. Please retry.',
    channel_d2c_title: 'Domestic Retail (D2C)',
    channel_d2c_sub: 'Retail price for individual domestic buyers',
    channel_b2b_title: 'Domestic Wholesale (B2B Bulk)',
    channel_b2b_sub: 'Bulk price and minimum order quantity',
    channel_export_title: 'DNK Global Export',
    channel_export_sub: 'Foreign export price in USD',
    moq_label: 'Minimum Order Quantity (MOQ)',
    export_viable_approved: 'Export Compliance Approved',
    export_viable_warning: 'Customs Review Advised',
    pkg_weight: 'Package Weight (Grams)',
    pkg_box_size: 'Standard Box Size',
    is_fragile: 'Fragile Handicraft',
    btn_publish: 'Publish Product',
    publishing: 'Publishing product to marketplace...',
    publish_success: 'Product successfully published!',
    draft_saved_local: 'Draft saved locally on device (Offline)',
    orders_title: 'Orders & Postal Manifest Hub',
    orders_subtitle: 'Track domestic & global export orders and generate DNK Postal Manifest QR codes.',
    tab_all: 'All',
    tab_d2c: 'D2C Retail',
    tab_b2b: 'B2B Wholesale',
    tab_export: 'Global Export',
    status_pending: 'Pending Drop-off',
    status_dropped: 'Received at Post Office',
    status_in_transit: 'In Transit',
    status_delivered: 'Delivered',
    btn_show_qr: 'Show Postal Manifest QR',
    btn_close_qr: 'Hide QR Code',
    tracking_unavailable: 'Tracking information unavailable',
    qr_title: 'Postal Counter Acceptance QR',
    qr_sub: 'Present this QR code to the postal operator at the counter',
    tracking_code: 'Postal Tracking Number',
    btn_print_label: 'Print CN23 Label',
    dropoff_title: 'Nearest Dak Ghar Niryat Kendras',
    dropoff_sub: 'Find the nearest 5 postal drop-off centers for counter check-in',
    detecting_location: 'Detecting your GPS location...',
    permission_denied: 'Location permission required to find nearby post offices',
    permission_denied_desc: 'Location permission was denied. Please allow GPS in your device/browser settings.',
    gps_status: 'GPS Location',
    btn_retry_gps: 'Retry GPS',
    finding_nearest_centers: 'Finding nearest Dak Ghar Niryat Kendras...',
    no_centers_title: 'No Post Office Centers Found',
    no_centers_sub: 'No active Dak Ghar Niryat Kendras found within 25 km of your location.',
    label_pincode: 'PIN Code',
    label_hours: 'Working Hours',
    label_contact: 'Contact',
    open_maps: 'Navigate in Google Maps',
    distance_km: 'km away',
    logout: 'Logout',
    logout_confirm: 'Are you sure you want to log out of your artisan account?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    loading: 'Loading...',
    error_connection_title: 'Server Connection Issue',
    error_connection: 'Unable to connect to server. Please verify your connection.',
  },
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
  currentLang: 'hi', // Default to Hindi for rural Indian artisans
  isSpeaking: false,

  setLanguage: async (lang: SupportedLanguage) => {
    set({ currentLang: lang });
    try {
      await AsyncStorage.setItem(APP_CONFIG.STORAGE_KEYS.SELECTED_LANGUAGE, lang);
    } catch (err) {
      console.warn('[LanguageStore] Failed to persist language:', err);
    }
  },

  hydrateLanguage: async () => {
    try {
      const savedLang = await AsyncStorage.getItem(APP_CONFIG.STORAGE_KEYS.SELECTED_LANGUAGE);
      if (savedLang && ['hi', 'kn', 'ta', 'bn', 'en'].includes(savedLang)) {
        set({ currentLang: savedLang as SupportedLanguage });
      }
    } catch (err) {
      console.warn('[LanguageStore] Failed to hydrate language:', err);
    }
  },

  t: (key: string): string => {
    const lang = get().currentLang;
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    if (dict[key]) return dict[key];
    return TRANSLATIONS.en[key] || key;
  },

  speakText: async (text: string) => {
    if (!text) return;
    const lang = get().currentLang;

    // Web Speech API execution on browser runtime
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      const bcp47Map: Record<SupportedLanguage, string> = {
        hi: 'hi-IN',
        kn: 'kn-IN',
        ta: 'ta-IN',
        bn: 'bn-IN',
        en: 'en-IN',
      };
      utterance.lang = bcp47Map[lang] || 'hi-IN';
      utterance.rate = 0.9;

      utterance.onstart = () => set({ isSpeaking: true });
      utterance.onend = () => set({ isSpeaking: false });
      utterance.onerror = () => set({ isSpeaking: false });

      set({ isSpeaking: true });
      window.speechSynthesis.speak(utterance);
    } else {
      console.log(`[Audio Narration] (${lang}): ${text}`);
    }
  },

  stopSpeaking: async () => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    set({ isSpeaking: false });
  },
}));

export default useLanguageStore;