import { create } from 'zustand';

export type SupportedLanguage = 'hi' | 'en' | 'bn' | 'ta' | 'kn' | 'te' | 'ml' | 'mr';

export interface ProductItem {
    id: string;
    title: Record<SupportedLanguage, string>;
    description: Record<SupportedLanguage, string>;
    category: string;
    hsCode: string;
    weight: string;
    priceInr: number;
    imageUri: string;
    status: 'ACTIVE_EXPORT' | 'DRAFT';
}

export interface ArtisanProfile {
    name: string;
    id: string;
    mobile: string;
    craftType: string;
    dnkCentre: string;
    bankAccount: string;
    ifscCode: string;
}

interface LanguageState {
    currentLang: SupportedLanguage;
    setLanguage: (lang: SupportedLanguage) => void;
    products: ProductItem[];
    addProduct: (product: ProductItem) => { success: boolean; error?: string };
    deleteProduct: (id: string) => void;
    profile: ArtisanProfile;
    updateProfile: (profile: Partial<ArtisanProfile>) => void;
    t: (key: string) => string;
}

const initialProfile: ArtisanProfile = {
    name: 'Karan Artisan',
    id: 'DNK-2026-8890',
    mobile: '+91 9829012345',
    craftType: 'Brass Artwork & Blue Pottery',
    dnkCentre: 'Jaipur GPO - 302001',
    bankAccount: '91829012345678',
    ifscCode: 'IPOS0000001',
};

const translations: Record<SupportedLanguage, Record<string, string>> = {
    en: {
        select_lang: "Select Language",
        login_title: "Artisan Login",
        login_sub: "Enter your registered details to access your export dashboard.",
        register_title: "New Artisan Registration",
        register_sub: "Register on the DNK Portal to start exporting globally.",
        full_name: "Full Name",
        craft_type: "Craft / Art Form",
        dnk_centre: "Nearest Post Office / DNK Centre",
        mobile_num: "Mob No.",
        password: "Password",
        btn_login: "Login →",
        btn_register: "Complete Registration →",
        no_account: "Don't have an account?",
        have_account: "Already have an account?",
        register: "Register",
        login_link: "Login here",
        forgot_password: "Forgot Password?",
        reg_success: "Registration Successful! Your DNK Artisan ID has been generated.",
        module_a_title: "Voice-First Product Onboarding",
        module_a_sub: "Speak in your native language. AI extracts title, category, weight, and HS code.",
        mic_instruction: "Tap Mic to Record Voice",
        stop_mic: "Stop Recording",
        voice_done: "✓ Voice Recorded",
        take_photo: "Capture / Upload Product Photo",
        photo_captured: "✓ Photo Added!",
        change_photo: "Change Photo",
        discard_photo: "✕ Discard",
        generate_catalog: "Generate AI Catalog",
        processing_ai: "AI is analyzing voice & image...",
        ai_preview_title: "AI Generated Product Catalog",
        ai_preview_sub: "Review the AI-extracted details below before confirming.",
        prod_name_label: "Product Title",
        prod_desc_label: "Description",
        hs_code_label: "Auto HS Code",
        weight_label: "Weight",
        est_price_label: "Price",
        btn_confirm_add: "✓ Confirm & Add to My Products",
        btn_cancel: "Discard & Try Again",
        tab_home: "Home",
        tab_add: "Add Item",
        tab_products: "My Products",
        tab_orders: "Drop-off & Labels",
        tab_payouts: "Payouts & Escrow",
        tab_settings: "Settings",
        help_support: "Help & Support",
        logout: "Logout",
        logout_confirm: "Are you sure you want to log out of your DNK Artisan account?",
        settings_title: "Artisan Profile & Settings",
        settings_sub: "View and edit your registered DNK artisan details.",
        bank_account: "Bank Account / Payout Account",
        ifsc_code: "IFSC / Branch Code",
        btn_save_changes: "Save Changes",
        profile_updated: "Profile details updated successfully!",
        my_products_title: "My Export Products",
        my_products_sub: "All verified items available on your global storefront",
        no_products_yet: "No products added yet. Use Voice AI to add your first item!",
        active_export_badge: "Ready for Export",
        delete_product: "Delete",
        duplicate_error: "This product already exists in your catalog!",
        delete_confirm: "Are you sure you want to delete this product?",
        add_product_title: "Add New Product",
        add_product_sub: "Voice AI onboarding & cataloging",
        dropoff_labels_title: "Drop-off & Labels",
        dropoff_labels_sub: "Check list of all drop-offs & print CN23",
        payout_status_title: "Payout Status",
        payout_status_sub: "Escrow releases & UPI transfers",
        escrow_summary_title: "Escrow Summary",
        escrow_summary_sub: "₹12,450.00 active in escrow vault",
        orders_screen_title: "Postal Drop-offs & CN23 Labels",
        orders_screen_sub: "Print postal labels and drop packages at your nearest DNK counter.",
        print_thermal_label: "🖨️ Print CN23 Thermal Label",
        label_printed_success: "CN23 Label sent to thermal printer successfully!",
        payouts_screen_title: "Bank Payouts & Escrow Vault",
        payouts_screen_sub: "Real-time tracking of escrow unlocks, bank transfers, and earnings.",
        escrow_locked_title: "Escrow Vault Balance",
        escrow_locked_sub: "Held securely by India Post until customs/counter scan",
        payout_history_title: "Recent Completed Transfers",
    },
    hi: {
        select_lang: "भाषा चुनें",
        login_title: "कारीगर लॉगिन",
        login_sub: "अपने निर्यात डैशबोर्ड तक पहुंचने के लिए अपने पंजीकृत विवरण दर्ज करें।",
        register_title: "नया कारीगर पंजीकरण",
        register_sub: "DNK पोर्टल पर रजिस्टर करें और वैश्विक निर्यात शुरू करें।",
        full_name: "पूरा नाम",
        craft_type: "शिल्प कला का प्रकार",
        dnk_centre: "निकटतम डाकघर / DNK केंद्र",
        mobile_num: "मोबाइल नंबर",
        password: "पासवर्ड",
        btn_login: "लॉगिन करें →",
        btn_register: "पंजीकरण पूरा करें →",
        no_account: "खाता नहीं है?",
        have_account: "पहले से खाता है?",
        register: "पंजीकरण करें",
        login_link: "लॉगिन करें",
        forgot_password: "पासवर्ड भूल गए?",
        reg_success: "पंजीकरण सफल! आपकी DNK कारीगर आईडी जेनरेट हो गई है।",
        module_a_title: "बोल कर सामान जोड़ें (AI वॉइस कैटलॉग)",
        module_a_sub: "अपनी स्थानीय भाषा में बोलें। AI स्वचालित रूप से शीर्षक, विवरण और HS कोड निकालेगा।",
        mic_instruction: "बोलने के लिए माइक दबाएं",
        stop_mic: "रिकॉर्डिंग रोकें",
        voice_done: "✓ आवाज रिकॉर्ड हुई",
        take_photo: "उत्पाद की फोटो चुनें/खींचें",
        photo_captured: "✓ फोटो जोड़ी गई!",
        change_photo: "फोटो बदलें",
        discard_photo: "✕ हटाएं",
        generate_catalog: "AI कैटलॉग तैयार करें",
        processing_ai: "AI विश्लेषण कर रहा है...",
        ai_preview_title: "AI कैटलॉग पूर्वावलोकन",
        ai_preview_sub: "कन्फर्म करने से पहले विवरण की जाँच करें।",
        prod_name_label: "उत्पाद का नाम",
        prod_desc_label: "विवरण",
        hs_code_label: "स्वचालित HS कोड",
        weight_label: "वजन",
        est_price_label: "मूल्य",
        btn_confirm_add: "✓ पुष्टि करें और मेरे सामान में जोड़ें",
        btn_cancel: "रद्द करें",
        tab_home: "होम",
        tab_add: "नया सामान",
        tab_products: "मेरे सामान",
        tab_orders: "ड्रॉप-ऑफ एवं लेबल",
        tab_payouts: "भुगतान एवं एस्क्रो",
        tab_settings: "सेटिंग्स",
        help_support: "सहायता एवं समर्थन",
        logout: "लॉग आउट",
        logout_confirm: "क्या आप वाकई अपने DNK कारीगर खाते से लॉग आउट करना चाहते हैं?",
        settings_title: "कारीगर प्रोफ़ाइल एवं सेटिंग्स",
        settings_sub: "अपने पंजीकृत DNK कारीगर विवरण देखें और संपादित करें।",
        bank_account: "बैंक खाता संख्या",
        ifsc_code: "IFSC कोड",
        btn_save_changes: "विवरण सुरक्षित करें",
        profile_updated: "प्रोफ़ाइल विवरण सफलतापूर्वक अपडेट किया गया!",
        my_products_title: "मेरे निर्यात उत्पाद",
        my_products_sub: "वैश्विक स्टोरफ्रंट पर उपलब्ध आपके सभी सत्यापित उत्पाद",
        no_products_yet: "अभी तक कोई उत्पाद नहीं जोड़ा गया है।",
        active_export_badge: "निर्यात के लिए तैयार",
        delete_product: "हटाएं",
        duplicate_error: "यह उत्पाद आपके कैटलॉग में पहले से मौजूद है!",
        delete_confirm: "क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?",
        add_product_title: "नया सामान जोड़ें",
        add_product_sub: "वॉइस AI द्वारा तुरंत कैटलॉग बनाएं",
        dropoff_labels_title: "डाकघर ड्रॉप-ऑफ एवं लेबल",
        dropoff_labels_sub: "ड्रॉप-ऑफ लिस्ट देखें और CN23 लेबल प्रिंट करें",
        payout_status_title: "बैंक भुगतान स्थिति",
        payout_status_sub: "एस्क्रो रिलीज एवं सीधे बैंक ट्रांसफर",
        escrow_summary_title: "एस्क्रो सारांश",
        escrow_summary_sub: "₹12,450.00 सुरक्षित एस्क्रो में उपलब्ध",
        orders_screen_title: "डाकघर ड्रॉप-ऑफ एवं CN23 लेबल",
        orders_screen_sub: "पार्सल लेबल प्रिंट करें और नजदीकी DNK काउंटर पर ड्रॉप करें।",
        print_thermal_label: "🖨️ CN23 थर्मल लेबल प्रिंट करें",
        label_printed_success: "CN23 लेबल सफलतापूर्वक प्रिंटर पर भेजा गया!",
        payouts_screen_title: "बैंक भुगतान एवं एस्क्रो तिजोरी",
        payouts_screen_sub: "एस्क्रो रिलीज, बैंक ट्रांसफर और कमाई का रीयल-टाइम विवरण।",
        escrow_locked_title: "एस्क्रो तिजोरी शेष राशि",
        escrow_locked_sub: "डाकघर स्कैन तक इंडिया पोस्ट द्वारा सुरक्षित रखा गया",
        payout_history_title: "हाल ही में पूरे हुए बैंक ट्रांसफर",
    },
    kn: {
        select_lang: "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        login_title: "ಕುಶಲಕರ್ಮಿ ಲಾಗಿನ್",
        login_sub: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
        register_title: "ಹೊಸ ಕುಶಲಕರ್ಮಿ ನೋಂದಣಿ",
        register_sub: "DNK ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ನೋಂದಾಯಿಸಿ.",
        full_name: "ಪೂರ್ಣ ಹೆಸರು",
        craft_type: "ಕುಶಲಕಲೆ ಪ್ರಕಾರ",
        dnk_centre: "ಹತ್ತಿರದ ಅಂಚೆ ಕಚೇರಿ",
        mobile_num: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
        password: "ಪಾಸ್‌ವರ್ಡ್",
        btn_login: "ಲಾಗಿನ್ ಮಾಡಿ →",
        btn_register: "ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ →",
        no_account: "ಖಾತೆ ಇಲ್ಲವೇ?",
        have_account: "ಖಾತೆ ಇದೆಯೇ?",
        register: "ನೋಂದಾಯಿಸಿ",
        login_link: "ಲಾಗಿನ್ ಮಾಡಿ",
        forgot_password: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
        reg_success: "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
        module_a_title: "ಧ್ವನಿಯ ಮೂಲಕ ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        module_a_sub: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ.",
        mic_instruction: "ರೆಕಾರ್ಡ್ ಮಾಡಲು ಮೈಕ್ ಒತ್ತಿ",
        stop_mic: "ನಿಲ್ಲಿಸಿ",
        voice_done: "✓ ಧ್ವನಿ ರೆಕಾರ್ಡ್ ಆಗಿದೆ",
        take_photo: "ಉತ್ಪನ್ನದ ಫೋಟೋ ಸೇರಿಸಿ",
        photo_captured: "✓ ಫೋಟೋ ಸೇರಿಸಲಾಗಿದೆ!",
        change_photo: "ಫೋಟೋ ಬದಲಾಯಿಸಿ",
        discard_photo: "✕ ಅಳಿಸಿ",
        generate_catalog: "AI ಕ್ಯಾಟಲಾಗ್ ಸಿದ್ಧಪಡಿಸಿ",
        processing_ai: "AI ವಿವರಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತಿದೆ...",
        ai_preview_title: "AI ಕ್ಯಾಟಲಾಗ್ ಪ್ರಿವ್ಯೂ",
        ai_preview_sub: "ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.",
        prod_name_label: "ಹೆಸರು",
        prod_desc_label: "ವಿವರಣೆ",
        hs_code_label: "HS ಕೋಡ್",
        weight_label: "ತೂಕ",
        est_price_label: "ಬೆಲೆ",
        btn_confirm_add: "✓ ದೃಢೀಕರಿಸಿ ಮತ್ತು ಸೇರಿಸಿ",
        btn_cancel: "ರದ್ದುಮಾಡಿ",
        tab_home: "ಮುಖಪುಟ",
        tab_add: "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        tab_products: "ನನ್ನ ಉತ್ಪನ್ನಗಳು",
        tab_orders: "ಡ್ರಾಪ್-ಆಫ್ & ಲೇಬಲ್‌ಗಳು",
        tab_payouts: "ಪಾವತಿ & ಎಸ್ಕ್ರೊ",
        tab_settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        help_support: "ಸಹಾಯ",
        logout: "ಲಾಗ್ ಔಟ್",
        logout_confirm: "ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
        settings_title: "ಕುಶಲಕರ್ಮಿ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        settings_sub: "ನಿಮ್ಮ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ಬದಲಾಯಿಸಿ.",
        bank_account: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ",
        ifsc_code: "IFSC ಕೋಡ್",
        btn_save_changes: "ಉಳಿಸಿ",
        profile_updated: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ!",
        my_products_title: "ನನ್ನ ರಫ್ತು ಉತ್ಪನ್ನಗಳು",
        my_products_sub: "ಗ್ಲೋಬಲ್ ಸ್ಟೋರ್‌ನಲ್ಲಿ ಲಭ್ಯವಿರುವ ಉತ್ಪನ್ನಗಳು",
        no_products_yet: "ಇನ್ನೂ ಯಾವುದೇ ಉತ್ಪನ್ನ ಸೇರಿಸಿಲ್ಲ.",
        active_export_badge: "ರಫ್ತಿಗೆ ಸಿದ್ಧವಾಗಿದೆ",
        delete_product: "ಅಳಿಸಿ",
        duplicate_error: "ಈ ಉತ್ಪನ್ನವು ಈಗಾಗಲೇ ನಿಮ್ಮ ಪಟ್ಟಿಯಲ್ಲಿದೆ!",
        delete_confirm: "ಈ ಉತ್ಪನ್ನವನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
        add_product_title: "ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        add_product_sub: "ಧ್ವನಿ AI ಮೂಲಕ ಕ್ಯಾಟಲಾಗ್ ರಚನೆ",
        dropoff_labels_title: "ಅಂಚೆ ಕಚೇರಿ ಡ್ರಾಪ್-ಆಫ್ & ಲೇಬಲ್‌ಗಳು",
        dropoff_labels_sub: "CN23 ಲೇಬಲ್ ಮುದ್ರಿಸಿ",
        payout_status_title: "ಪಾವತಿ ಸ್ಥಿತಿ",
        payout_status_sub: "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ ವಿವರ",
        escrow_summary_title: "ಎಸ್ಕ್ರೊ ಬ್ಯಾಲೆನ್ಸ್",
        escrow_summary_sub: "₹12,450.00 ಸುರಕ್ಷಿತ ಎಸ್ಕ್ರೊ ಖಾತೆಯಲ್ಲಿದೆ",
        orders_screen_title: "ಅಂಚೆ ಕಚೇರಿ ಡ್ರಾಪ್-ಆಫ್ ಮತ್ತು CN23 ಲೇಬಲ್",
        orders_screen_sub: "CN23 ಲೇಬಲ್ ಮುದ್ರಿಸಿ DNK ಕೌಂಟರ್‌ಗೆ ತಲುಪಿಸಿ.",
        print_thermal_label: "🖨️ CN23 ಲೇಬಲ್ ಮುದ್ರಿಸಿ",
        label_printed_success: "ಲೇಬಲ್ ಮುದ್ರಣಕ್ಕೆ ಕಳುಹಿಸಲಾಗಿದೆ!",
        payouts_screen_title: "ಬ್ಯಾಂಕ್ ಪಾವತಿಗಳು ಮತ್ತು ಎಸ್ಕ್ರೊ ವಾಲ್ಟ್",
        payouts_screen_sub: "ಪಾವತಿ ಮತ್ತು ಗಳಿಕೆಯ ವಿವರಗಳು.",
        escrow_locked_title: "ಎಸ್ಕ್ರೊ ವಾಲ್ಟ್ ಬ್ಯಾಲೆನ್ಸ್",
        escrow_locked_sub: "ಅಂಚೆ ಕಚೇರಿ ಸ್ಕ್ಯಾನ್ ಆಗುವವರೆಗೆ ಸುರಕ್ಷಿತವಾಗಿರುತ್ತದೆ",
        payout_history_title: "ಇತ್ತೀಚಿನ ಪಾವತಿಗಳು",
    },
    te: {
        select_lang: "భాషను ఎంచుకోండి",
        login_title: "కార్మికుల లాగిన్",
        login_sub: "వివరాలను నమోదు చేయండి.",
        register_title: "కొత్త ఆర్టిసన్ నమోదు",
        register_sub: "DNK లో నమోదు చేసుకోండి.",
        full_name: "పూర్తి పేరు",
        craft_type: "చేతివృత్తి రకం",
        dnk_centre: "సమీప పోస్ట్ ఆఫీస్",
        mobile_num: "మొబైల్ నంబర్",
        password: "పాస్వర్డ్",
        btn_login: "లాగిన్ చేయండి →",
        btn_register: "నమోదు పూర్తి చేయండి →",
        no_account: "ఖాతా లేదా?",
        have_account: "ఖాతా ఉందా?",
        register: "రిజిస్టర్ చేసుకోండి",
        login_link: "లాగిన్ చేయండి",
        forgot_password: "పాస్వర్డ్ మరచిపోయారా?",
        reg_success: "నమోదు విజయవంతమైంది!",
        module_a_title: "వాయిస్‌తో ప్రాడక్ట్ జోడించండి",
        module_a_sub: "మీ భాషలో మాట్లాడండి.",
        mic_instruction: "వాయిస్ రికార్డ్ చేయండి",
        stop_mic: "ఆపండి",
        voice_done: "✓ వాయిస్ రికార్డ్ అయింది",
        take_photo: "ఫోటో తీయండి",
        photo_captured: "✓ ఫోటో జోడించబడింది!",
        change_photo: "ఫోటో మార్చండి",
        discard_photo: "✕ తీసివేయండి",
        generate_catalog: "AI క్యాటలాగ్ సృష్టించండి",
        processing_ai: "AI విశ్లేషిస్తోంది...",
        ai_preview_title: "AI ప్రాడక్ట్ ప్రివ్యూ",
        ai_preview_sub: "వివరాలను సమీక్షించండి.",
        prod_name_label: "పేరు",
        prod_desc_label: "వివరణ",
        hs_code_label: "HS కోడ్",
        weight_label: "బరువు",
        est_price_label: "ధర",
        btn_confirm_add: "✓ నిర్ధారించండి & జోడించండి",
        btn_cancel: "రద్దు చేయండి",
        tab_home: "హోమ్",
        tab_add: "వస్తువు జోడించండి",
        tab_products: "నా ఉత్పత్తులు",
        tab_orders: "డ్రాప్-ఆఫ్ & లేబుల్స్",
        tab_payouts: "చెల్లింపులు & ఎస్క్రో",
        tab_settings: "సెట్టింగ్‌లు",
        help_support: "సహాయం",
        logout: "లాగ్ అవుట్",
        logout_confirm: "మీరు లాగ్ అవుట్ చేయాలనుకుంటున్నారా?",
        settings_title: "ఆర్టిసన్ ప్రొఫైల్ & సెట్టింగ్‌లు",
        settings_sub: "వివరాలను సవరించండి.",
        bank_account: "బ్యాంక్ ఖాతా నంబర్",
        ifsc_code: "IFSC కోడ్",
        btn_save_changes: "సేవ్ చేయండి",
        profile_updated: "ప్రొఫైల్ అప్‌డేట్ చేయబడింది!",
        my_products_title: "నా ఎగుమతి ఉత్పత్తులు",
        my_products_sub: "స్టోర్‌లో ఉన్న ఉత్పత్తులు",
        no_products_yet: "ఇంకా ఉత్పత్తులు లేవు.",
        active_export_badge: "ఎగుమతికి సిద్ధం",
        delete_product: "తొలగించండి",
        duplicate_error: "ఈ ఉత్పత్తి ఇప్పటికే ఉంది!",
        delete_confirm: "ఖచ్చితంగా తొలగించాలనుకుంటున్నారా?",
        add_product_title: "కొత్త వస్తువు జోడించండి",
        add_product_sub: "వాయిస్ AI క్యాటలాగింగ్",
        dropoff_labels_title: "డ్రాప్-ఆఫ్ & లేబుల్స్",
        dropoff_labels_sub: "CN23 లేబుల్ ముద్రించండి",
        payout_status_title: "చెల్లింపు స్థితి",
        payout_status_sub: "ఎస్క్రో మరియు UPI బదిలీలు",
        escrow_summary_title: "ఎస్క్రో సారాంశం",
        escrow_summary_sub: "₹12,450.00 ఎస్క్రో ఖాతాలో ఉంది",
        orders_screen_title: "డ్రాప్-ఆఫ్ & CN23 లేబుల్స్",
        orders_screen_sub: "లేబుల్ ముద్రించి పోస్ట్ ఆఫీస్ కౌంటర్‌లో డ్రాప్ చేయండి.",
        print_thermal_label: "🖨️ CN23 లేబుల్ ముద్రించండి",
        label_printed_success: "లేబుల్ ప్రింటర్‌కు పంపబడింది!",
        payouts_screen_title: "బ్యాంక్ చెల్లింపులు & ఎస్క్రో వాల్ట్",
        payouts_screen_sub: "చెల్లింపుల వివరాలు.",
        escrow_locked_title: "ఎస్క్రో వాల్ట్ బ్యాలెన్స్",
        escrow_locked_sub: "పోస్ట్ ఆఫీస్ స్కాన్ చేసేవరకు భద్రంగా ఉంటుంది",
        payout_history_title: "ఇటీవలి చెల్లింపులు",
    },
    ta: {
        select_lang: "மொழியைத் தேர்ந்தெடுக்கவும்",
        login_title: "கைவினைஞர் உள்நுழைவு",
        login_sub: "விவரங்களை உள்ளிடவும்.",
        register_title: "புதிய கைவினைஞர் பதிவு",
        register_sub: "பதிவு செய்யவும்.",
        full_name: "முழு பெயர்",
        craft_type: "கைவினை வகை",
        dnk_centre: "அஞ்சல் அலுவலகம்",
        mobile_num: "மொபைல் எண்",
        password: "கடவுச்சொல்",
        btn_login: "உள்நுழைக →",
        btn_register: "பதிவை முடிக்கவும் →",
        no_account: "கணக்கு இல்லையா?",
        have_account: "கணக்கு உள்ளதா?",
        register: "பதிவு செய்யவும்",
        login_link: "உள்நுழைக",
        forgot_password: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
        reg_success: "பதிவு முடிந்தது!",
        module_a_title: "குரல் மூலம் தயாரிப்பு சேர்ப்பு",
        module_a_sub: "உங்கள் மொழியில் பேசுங்கள்.",
        mic_instruction: "பதிவு செய்ய அழுத்தவும்",
        stop_mic: "நிறுத்து",
        voice_done: "✓ பதிவு செய்யப்பட்டது",
        take_photo: "படம் எடுக்கவும்",
        photo_captured: "✓ படம் சேர்க்கப்பட்டது!",
        change_photo: "படம் மாற்று",
        discard_photo: "✕ நீக்கு",
        generate_catalog: "AI கேடலாக் உருவாக்கவும்",
        processing_ai: "AI உருவாக்குகிறது...",
        ai_preview_title: "AI கேடலாக் முன்னோட்டம்",
        ai_preview_sub: "விவரங்களை சரிபார்க்கவும்.",
        prod_name_label: "பெயர்",
        prod_desc_label: "விளக்கம்",
        hs_code_label: "HS குறியீடு",
        weight_label: "எடை",
        est_price_label: "விலை",
        btn_confirm_add: "✓ உறுதிசெய்து சேர்க்கவும்",
        btn_cancel: "ரத்து செய்",
        tab_home: "முகப்பு",
        tab_add: "பொருள் சேர்க்க",
        tab_products: "என் பொருட்கள்",
        tab_orders: "ஒப்படைப்பு & லேபிள்கள்",
        tab_payouts: "செலுத்தல்கள் & எஸ்க்ரோ",
        tab_settings: "அமைப்புகள்",
        help_support: "உதவி",
        logout: "வெளியேறு",
        logout_confirm: "நீங்கள் வெளியேற விரும்புகிறீர்களா?",
        settings_title: "சுயவிவரம் & அமைப்புகள்",
        settings_sub: "உங்கள் விவரங்களைத் திருத்தவும்.",
        bank_account: "வங்கி கணக்கு எண்",
        ifsc_code: "IFSC குறியீடு",
        btn_save_changes: "சேமிக்கவும்",
        profile_updated: "சுயவிவரம் புதுப்பிக்கப்பட்டது!",
        my_products_title: "என் தயாரிப்புகள்",
        my_products_sub: "உலகளாவிய ஸ்டோரில் உள்ளவை",
        no_products_yet: "பொருட்கள் எதுவும் இல்லை.",
        active_export_badge: "ஏற்றுமதிக்கு தயார்",
        delete_product: "நீக்கு",
        duplicate_error: "இந்த தயாரிப்பு ஏற்கனவே உள்ளது!",
        delete_confirm: "இதை நீக்க விரும்புகிறீர்களா?",
        add_product_title: "புதிய பொருள் சேர்க்கவும்",
        add_product_sub: "குரல் AI கேடலாக் சேர்ப்பு",
        dropoff_labels_title: "ஒப்படைப்பு & லேபிள்கள்",
        dropoff_labels_sub: "CN23 லேபிள் அச்சிடுக",
        payout_status_title: "பணம் செலுத்தல் நிலை",
        payout_status_sub: "வங்கி பரிமாற்ற விவரம்",
        escrow_summary_title: "எஸ்க்ரோ விவரம்",
        escrow_summary_sub: "₹12,450.00 எஸ்க்ரோவில் உள்ளது",
        orders_screen_title: "அஞ்சல் ஒப்படைப்பு & CN23 லேபிள்",
        orders_screen_sub: "லேபிளை அச்சிட்டு DNK கவுண்டரில் ஒப்படைக்கவும்.",
        print_thermal_label: "🖨️ CN23 லேபிள் அச்சிடுக",
        label_printed_success: "லேபிள் அச்சிட அனுப்பப்பட்டது!",
        payouts_screen_title: "வங்கி செலுத்தல்கள் & எஸ்க்ரோ",
        payouts_screen_sub: "வருவாய் மற்றும் கணக்கு விவரங்கள்.",
        escrow_locked_title: "எஸ்க்ரோ இருப்பு",
        escrow_locked_sub: "அஞ்சல் அலுவலக ஸ்கேன் வரை பாதுகாப்பாக வைக்கப்பட்டுள்ளது",
        payout_history_title: "சமீபத்திய பரிமாற்றங்கள்",
    },
    ml: {
        select_lang: "ഭാഷ തിരഞ്ഞെടുക്കുക",
        login_title: "ലോഗിൻ",
        login_sub: "വിവരങ്ങൾ നൽകുക.",
        register_title: "രജിസ്ട്രേഷൻ",
        register_sub: "രജിസ്റ്റർ ചെയ്യുക.",
        full_name: "പേര്",
        craft_type: "കരകൗശല തരം",
        dnk_centre: "പോസ്റ്റ് ഓഫീസ്",
        mobile_num: "മൊബൈൽ നമ്പർ",
        password: "പാസ്‌വേഡ്",
        btn_login: "ലോഗിൻ →",
        btn_register: "രജിസ്റ്റർ ചെയ്യുക →",
        no_account: "അക്കൗണ്ട് ഇല്ലേ?",
        have_account: "അക്കൗണ്ട് ഉണ്ടോ?",
        register: "രജിസ്റ്റർ ചെയ്യുക",
        login_link: "ലോഗിൻ ചെയ്യുക",
        forgot_password: "പാസ്‌വേഡ് മറന്നോ?",
        reg_success: "വിജയകരമായി പൂർത്തിയായി!",
        module_a_title: "ശബ്ദത്തിലൂടെ ഉൽപ്പന്നം ചേർക്കുക",
        module_a_sub: "നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക.",
        mic_instruction: "റെക്കോർഡ് ചെയ്യാൻ ടാപ്പ് ചെയ്യുക",
        stop_mic: "നിർത്തുക",
        voice_done: "✓ ശബ്ദം റെക്കോർഡ് ചെയ്തു",
        take_photo: "ഫോട്ടോ എടുക്കുക",
        photo_captured: "✓ ഫോട്ടോ ചേർത്തു!",
        change_photo: "ഫോട്ടോ മാറ്റുക",
        discard_photo: "✕ ഒഴിവാക്കുക",
        generate_catalog: "AI കാറ്റലോഗ് നിർമ്മിക്കുക",
        processing_ai: "AI പരിശോധിക്കുന്നു...",
        ai_preview_title: "AI കാറ്റലോഗ് പ്രിവ്യൂ",
        ai_preview_sub: "വിവരങ്ങൾ പരിശോധിക്കുക.",
        prod_name_label: "പേര്",
        prod_desc_label: "വിവരണം",
        hs_code_label: "HS കോഡ്",
        weight_label: "ഭാരം",
        est_price_label: "വില",
        btn_confirm_add: "✓ സ്ഥിരീകരിച്ച് ചേർക്കുക",
        btn_cancel: "റദ്ദാക്കുക",
        tab_home: "ഹോം",
        tab_add: "ചേർക്കുക",
        tab_products: "എന്റെ ഉൽപ്പന്നങ്ങൾ",
        tab_orders: "ഡ്രോപ്പ്-ഓഫ് & ലേബലുകൾ",
        tab_payouts: "പേയ്‌മെന്റുകൾ & എസ്‌ക്രോ",
        tab_settings: "ക്രമീകരണങ്ങൾ",
        help_support: "സഹായം",
        logout: "ലോഗ് ഔട്ട്",
        logout_confirm: "നിങ്ങൾക്ക് ലോഗ് ഔട്ട് ചെയ്യണോ?",
        settings_title: "പ്രൊഫൈൽ & ക്രമീകരണങ്ങൾ",
        settings_sub: "വിവരങ്ങൾ എഡിറ്റ് ചെയ്യുക.",
        bank_account: "ബാങ്ക് അക്കൗണ്ട് നമ്പർ",
        ifsc_code: "IFSC കോഡ്",
        btn_save_changes: "സേവ് ചെയ്യുക",
        profile_updated: "പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്തു!",
        my_products_title: "എന്റെ ഉൽപ്പന്നങ്ങൾ",
        my_products_sub: "ലഭ്യമായ ഇനങ്ങൾ",
        no_products_yet: "ഉൽപ്പന്നങ്ങൾ ചേർത്തിട്ടില്ല.",
        active_export_badge: "കയറ്റുമതിക്ക് തയ്യാറാണ്",
        delete_product: "ഡിലീറ്റ് ചെയ്യുക",
        duplicate_error: "ഈ ഉൽപ്പന്നം ഇതിനകം ഉണ്ട്!",
        delete_confirm: "നീക്കം ചെയ്യണോ?",
        add_product_title: "പുതിയ ഉൽപ്പന്നം ചേർക്കുക",
        add_product_sub: "വോയ്‌സ് AI കാറ്റലോഗിംഗ്",
        dropoff_labels_title: "ഡ്രോപ്പ്-ഓഫ് & ലേബലുകൾ",
        dropoff_labels_sub: "CN23 ലേബൽ പ്രിന്റ് ചെയ്യുക",
        payout_status_title: "പേയ്‌മെന്റ് നില",
        payout_status_sub: "എസ്‌ക്രോ & ബാങ്ക് ട്രാൻസ്ഫർ",
        escrow_summary_title: "എസ്‌ക്രോ ബാലൻസ്",
        escrow_summary_sub: "₹12,450.00 എസ്‌ക്രോയിൽ ഉണ്ട്",
        orders_screen_title: "തപാൽ ഡ്രോപ്പ്-ഓഫുകൾ & CN23 ലേബലുകൾ",
        orders_screen_sub: "ലേബൽ പ്രിന്റ് ചെയ്ത് പോസ്റ്റ് ഓഫീസിൽ നൽകുക.",
        print_thermal_label: "🖨️ CN23 ലേബൽ പ്രിന്റ് ചെയ്യുക",
        label_printed_success: "ലേബൽ പ്രിന്ററിലേക്ക് അയച്ചു!",
        payouts_screen_title: "ബാങ്ക് പേയ്‌മെന്റുകൾ & എസ്‌ക്രോ",
        payouts_screen_sub: "വരുമാന വിവരങ്ങൾ.",
        escrow_locked_title: "എസ്‌ക്രോ ബാലൻസ്",
        escrow_locked_sub: "പോസ്റ്റ് ഓഫീസ് സ്കാൻ വരെ സുരക്ഷിതമാണ്",
        payout_history_title: "സമീപകാല ഇടപാടുകൾ",
    },
    mr: {
        select_lang: "भाषा निवडा",
        login_title: "कारागीर लॉगिन",
        login_sub: "तपशील टाका.",
        register_title: "नवीन नोंदणी",
        register_sub: "नोंदणी करा.",
        full_name: "पूर्ण नाव",
        craft_type: "हस्तकला प्रकार",
        dnk_centre: "टपाल कार्यालय",
        mobile_num: "मोबाईल नंबर",
        password: "पासवर्ड",
        btn_login: "लॉगिन करा →",
        btn_register: "नोंदणी करा →",
        no_account: "खाते नाही?",
        have_account: "खाते आहे?",
        register: "नोंदणी करा",
        login_link: "लॉगिन करा",
        forgot_password: "पासवर्ड विसरलात?",
        reg_success: "नोंदणी यशस्वी झाली!",
        module_a_title: "बोलून वस्तू जोडा (AI व्हॉइस)",
        module_a_sub: "तुमच्या भाषेत बोला.",
        mic_instruction: "माइकवर टॅप करा",
        stop_mic: "थांबवा",
        voice_done: "✓ आवाज रेकॉर्ड झाला",
        take_photo: "फोटो जोडा",
        photo_captured: "✓ फोटो जोडला गेला!",
        change_photo: "फोटो बदला",
        discard_photo: "✕ हटवा",
        generate_catalog: "AI कॅटलॉग तयार करा",
        processing_ai: "AI विश्लेषण करत आहे...",
        ai_preview_title: "AI कॅटलॉग पूर्वावलोकन",
        ai_preview_sub: "तपशील तपासा.",
        prod_name_label: "नाव",
        prod_desc_label: "वर्णन",
        hs_code_label: "HS कोड",
        weight_label: "वजन",
        est_price_label: "किंमत",
        btn_confirm_add: "✓ पुष्टी करा आणि जोडा",
        btn_cancel: "रद्द करा",
        tab_home: "होम",
        tab_add: "वस्तू जोडा",
        tab_products: "माझी उत्पादने",
        tab_orders: "ड्रॉप-ऑफ आणि लेबल",
        tab_payouts: "पेमेंट आणि एस्क्रॉ",
        tab_settings: "सेटिंग्ज",
        help_support: "मदत आणि सपोर्ट",
        logout: "लॉग आउट",
        logout_confirm: "तुम्हाला तुमच्या खात्यातून लॉग आउट करायचे आहे का?",
        settings_title: "कारागीर प्रोफाइल आणि सेटिंग्ज",
        settings_sub: "तुमचा नोंदणीकृत तपशील संपादित करा.",
        bank_account: "बँक खाते क्रमांक",
        ifsc_code: "IFSC कोड",
        btn_save_changes: "बदल जतन करा",
        profile_updated: "प्रोफाइल यशस्वीरित्या अपडेट केले!",
        my_products_title: "माझी उत्पादने",
        my_products_sub: "उपलब्ध उत्पादने",
        no_products_yet: "उत्पादने जोडली नाहीत.",
        active_export_badge: "निर्यातीसाठी सज्ज",
        delete_product: "हटवा",
        duplicate_error: "हे उत्पादन आधीपासून अस्तित्वात आहे!",
        delete_confirm: "तुम्हाला हे उत्पादन हटवायचे आहे का?",
        add_product_title: "नवीन वस्तू जोडा",
        add_product_sub: "व्हॉईस AI द्वारे कॅटलॉग निर्मिती",
        dropoff_labels_title: "ड्रॉप-ऑफ आणि लेबल",
        dropoff_labels_sub: "CN23 लेबल प्रिंट करा",
        payout_status_title: "पेमेंट स्थिती",
        payout_status_sub: "एस्क्रॉ आणि बँक ट्रान्सफर",
        escrow_summary_title: "एस्क्रॉ तपशील",
        escrow_summary_sub: "₹12,450.00 एस्क्रॉमध्ये सक्रिय",
        orders_screen_title: "टपाल कार्यालय ड्रॉप-ऑफ आणि CN23 लेबल्स",
        orders_screen_sub: "पार्सल लेबल प्रिंट करा आणि जवळच्या DNK काउंटरवर ड्रॉप करा.",
        print_thermal_label: "🖨️ CN23 लेबल प्रिंट करा",
        label_printed_success: "लेबल प्रिंटरवर पाठवले गेले!",
        payouts_screen_title: "बँक पेमेंट्स आणि एस्क्रॉ व्हॉल्ट",
        payouts_screen_sub: "पेमेंट आणि कमाईचा तपशील.",
        escrow_locked_title: "एस्क्रॉ शिल्लक",
        escrow_locked_sub: "पोस्ट ऑफिस स्कॅन होईपर्यंत सुरक्षित",
        payout_history_title: "अलीकडील बँक ट्रान्सफर",
    },
    bn: {
        select_lang: "भाषा নির্বাচন করুন",
        login_title: "লগইন",
        login_sub: "বিস্তারিত লিখুন।",
        register_title: "নিবন্ধন",
        register_sub: "নিবন্ধন করুন।",
        full_name: "পুরো নাম",
        craft_type: "হস্তশিল্পের ধরন",
        dnk_centre: "পোস্ট অফিস",
        mobile_num: "মোবাইল নম্বর",
        password: "পাসওয়ার্ড",
        btn_login: "লগইন →",
        btn_register: "নিবন্ধন →",
        no_account: "অ্যাকাউন্ট নেই?",
        have_account: "অ্যাকাউন্ট আছে?",
        register: "নিবন্ধন করুন",
        login_link: "লগইন করুন",
        forgot_password: "পাসওয়ার্ড ভুলে গেছেন?",
        reg_success: "নিবন্ধন সম্পন্ন হয়েছে!",
        module_a_title: "কণ্ঠে পণ্য যোগ করুন",
        module_a_sub: "আপনার মাতৃভাষায় কথা বলুন।",
        mic_instruction: "মাইকে ট্যাপ করুন",
        stop_mic: "থামান",
        voice_done: "✓ ভয়েস রেকর্ড হয়েছে",
        take_photo: "ছবি যোগ করুন",
        photo_captured: "✓ ছবি যোগ করা হয়েছে!",
        change_photo: "ছবি পরিবর্তন",
        discard_photo: "✕ মুছুন",
        generate_catalog: "AI ক্যাটালগ তৈরি করুন",
        processing_ai: "AI বিশ্লেষণ করছে...",
        ai_preview_title: "AI ক্যাটালগ পূর্বরূপ",
        ai_preview_sub: "বিবরণ পরীক্ষা করুন।",
        prod_name_label: "নাম",
        prod_desc_label: "বিবরণ",
        hs_code_label: "HS কোড",
        weight_label: "ওজন",
        est_price_label: "মূল্য",
        btn_confirm_add: "✓ নিশ্চিত করুন এবং যোগ করুন",
        btn_cancel: "বাতিল করুন",
        tab_home: "হোম",
        tab_add: "পণ্য যোগ",
        tab_products: "আমার পণ্য",
        tab_orders: "ড্রপ-অফ এবং লেবেল",
        tab_payouts: "পেমেন্ট এবং এসক্রো",
        tab_settings: "সেটিংস",
        help_support: "সহায়তা",
        logout: "লগ আউট",
        logout_confirm: "আপনি কি সত্যিই লগ আউট করতে চান?",
        settings_title: "প্রোফাইল এবং সেটিংস",
        settings_sub: "আপনার নিবন্ধিত বিবরণ সম্পাদনা করুন।",
        bank_account: "ব্যাংক অ্যাকাউন্ট নম্বর",
        ifsc_code: "IFSC কোড",
        btn_save_changes: "সংরক্ষণ করুন",
        profile_updated: "প্রোফাইল আপডেট হয়েছে!",
        my_products_title: "আমার পণ্যসমূহ",
        my_products_sub: "উপলব্ধ আইটেম",
        no_products_yet: "পণ্য যোগ করা হয়নি।",
        active_export_badge: "রফতানির জন্য প্রস্তুত",
        delete_product: "মুছুন",
        duplicate_error: "এই পণ্যটি ইতিমধ্যে রয়েছে!",
        delete_confirm: "মুছতে চান?",
        add_product_title: "নতুন পণ্য যোগ করুন",
        add_product_sub: "ভয়েস AI ক্যাটালগিং",
        dropoff_labels_title: "ড্রপ-অফ এবং লেবেল",
        dropoff_labels_sub: "CN23 লেবেল মুদ্রণ করুন",
        payout_status_title: "পেমেন্ট স্থিতি",
        payout_status_sub: "এসক্রো এবং ব্যাংক স্থানান্তর",
        escrow_summary_title: "এসক্রো সারসংক্ষেপ",
        escrow_summary_sub: "₹12,450.00 এসক্রো ভল্টে আছে",
        orders_screen_title: "পোস্ট অফিস ড্রপ-অফ ও CN23 লেবেল",
        orders_screen_sub: "লেবেল মুদ্রণ করুন এবং নিকটস্থ DNK কাউন্টারে জমা দিন।",
        print_thermal_label: "🖨️ CN23 লেবেল মুদ্রণ করুন",
        label_printed_success: "লেবেল প্রিন্টারে পাঠানো হয়েছে!",
        payouts_screen_title: "ব্যাংক পেমেন্ট এবং এসক্রো ভল্ট",
        payouts_screen_sub: "রিয়েল-টাইম পেমেন্ট বিবরণ।",
        escrow_locked_title: "এসক্রো ব্যালেন্স",
        escrow_locked_sub: "পোস্ট অফিস স্ক্যান হওয়া পর্যন্ত সুরক্ষিত",
        payout_history_title: "সাম্প্রতিক স্থানান্তর",
    }
};

export const useLanguageStore = create<LanguageState>((set, get) => ({
    currentLang: 'en',
    setLanguage: (lang) => set({ currentLang: lang }),
    products: [],
    addProduct: (newProduct) => {
        const existing = get().products;
        const isDuplicate = existing.some(
            (p) => p.title.en.trim().toLowerCase() === newProduct.title.en.trim().toLowerCase()
        );

        if (isDuplicate) {
            return { success: false, error: get().t('duplicate_error') };
        }

        set({ products: [newProduct, ...existing] });
        return { success: true };
    },
    deleteProduct: (id) => set((state) => ({
        products: state.products.filter((p) => p.id !== id),
    })),
    profile: initialProfile,
    updateProfile: (updatedData) => set((state) => ({
        profile: { ...state.profile, ...updatedData }
    })),
    t: (key) => {
        const lang = get().currentLang;
        return translations[lang]?.[key] || translations['en']?.[key] || key;
    }
}));