from typing import Optional
from pydantic import BaseModel, Field


class TranscriptionResponse(BaseModel):
    filename: str = Field(..., description="Uploaded audio filename")
    transcript: str = Field(..., description="Raw text transcript generated by Whisper")
    detected_language: Optional[str] = Field(
        default=None, 
        description="Detected audio spoken language ISO code"
    )
    processing_time_seconds: float = Field(
        ..., 
        description="Time taken to process and transcribe audio"
    )